version: '3.8'

services:
  digiurban:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_TIMESTAMP=${BUILD_TIMESTAMP:-0}
        - DATABASE_URL=${DATABASE_URL}
    container_name: digiurban-vps
    ports:
      - "3060:80"  # Porta EXTERNA 3060 -> Porta INTERNA 80 (Nginx)
    environment:
      # Node.js
      - NODE_ENV=production

      # Backend (porta interna 3001)
      - PORT=3001
      - BACKEND_PORT=3001

      # Frontend (porta interna 3000)
      - FRONTEND_PORT=3000
      # NEXT_PUBLIC_API_URL é setado em BUILD TIME no Dockerfile (linha 40)
      # Não precisa ser setado aqui pois já foi injetado no build

      # Database
      - DATABASE_URL=${DATABASE_URL:-file:/app/data/dev.db}

      # JWT
      - JWT_SECRET=${JWT_SECRET:-digiurban-super-secret-change-in-production}
      - JWT_EXPIRES_IN=7d
      - JWT_ADMIN_EXPIRES_IN=8h
      - JWT_CITIZEN_EXPIRES_IN=30d

      # CORS (ambos domínios com e sem www)
      - FRONTEND_URL=https://digiurban.com.br
      - CORS_ORIGIN=https://digiurban.com.br
      - ALLOWED_ORIGINS=https://www.digiurban.com.br,https://digiurban.com.br,http://www.digiurban.com.br,http://digiurban.com.br,http://72.60.10.108:3060,http://localhost:3060

      # Tenants
      - DEFAULT_TENANT=demo

      # Logs
      - LOG_LEVEL=info

    volumes:
      - digiurban_data:/app/data
      - digiurban_uploads:/app/uploads
      - digiurban_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    networks:
      - digiurban_network

volumes:
  digiurban_data:
    driver: local
  digiurban_uploads:
    driver: local
  digiurban_logs:
    driver: local

networks:
  digiurban_network:
    driver: bridge
