-- CreateTable
CREATE TABLE "weeding_requests" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "tenantId" TEXT NOT NULL,
    "protocolId" TEXT,
    "citizenId" TEXT,
    "requestorName" TEXT NOT NULL,
    "requestorCpf" TEXT,
    "contact" JSONB NOT NULL,
    "location" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "coordinates" JSONB,
    "areaSize" REAL,
    "terrainType" TEXT NOT NULL,
    "accessType" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "photos" JSONB,
    "urgency" TEXT NOT NULL DEFAULT 'NORMAL',
    "requestDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "preferredDate" DATETIME,
    "scheduledDate" DATETIME,
    "completionDate" DATETIME,
    "assignedTeam" TEXT,
    "status" TEXT NOT NULL DEFAULT 'REQUESTED',
    "workDetails" TEXT,
    "equipmentUsed" JSONB,
    "workHours" REAL,
    "observations" TEXT,
    "satisfaction" INTEGER,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "weeding_requests_protocolId_fkey" FOREIGN KEY ("protocolId") REFERENCES "protocols_simplified" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "weeding_requests_citizenId_fkey" FOREIGN KEY ("citizenId") REFERENCES "citizens" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "weeding_requests_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "drainage_requests" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "tenantId" TEXT NOT NULL,
    "protocolId" TEXT,
    "citizenId" TEXT,
    "requestorName" TEXT NOT NULL,
    "requestorCpf" TEXT,
    "contact" JSONB NOT NULL,
    "location" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "coordinates" JSONB,
    "problemType" TEXT NOT NULL,
    "severity" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "photos" JSONB,
    "waterLevel" TEXT,
    "affectedArea" REAL,
    "urgency" TEXT NOT NULL DEFAULT 'HIGH',
    "requestDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "preferredDate" DATETIME,
    "scheduledDate" DATETIME,
    "completionDate" DATETIME,
    "assignedTeam" TEXT,
    "status" TEXT NOT NULL DEFAULT 'REQUESTED',
    "workDetails" TEXT,
    "equipmentUsed" JSONB,
    "materialsUsed" JSONB,
    "workHours" REAL,
    "observations" TEXT,
    "satisfaction" INTEGER,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "drainage_requests_protocolId_fkey" FOREIGN KEY ("protocolId") REFERENCES "protocols_simplified" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "drainage_requests_citizenId_fkey" FOREIGN KEY ("citizenId") REFERENCES "citizens" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "drainage_requests_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "tree_pruning_requests" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "tenantId" TEXT NOT NULL,
    "protocolId" TEXT,
    "citizenId" TEXT,
    "requestorName" TEXT NOT NULL,
    "requestorCpf" TEXT,
    "contact" JSONB NOT NULL,
    "location" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "coordinates" JSONB,
    "treeSpecies" TEXT,
    "treeHeight" REAL,
    "trunkDiameter" REAL,
    "pruningType" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "photos" JSONB,
    "riskLevel" TEXT,
    "urgency" TEXT NOT NULL DEFAULT 'NORMAL',
    "requestDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "preferredDate" DATETIME,
    "scheduledDate" DATETIME,
    "completionDate" DATETIME,
    "assignedTeam" TEXT,
    "technicalVisit" BOOLEAN NOT NULL DEFAULT false,
    "visitDate" DATETIME,
    "approved" BOOLEAN,
    "approvalNotes" TEXT,
    "status" TEXT NOT NULL DEFAULT 'REQUESTED',
    "workDetails" TEXT,
    "equipmentUsed" JSONB,
    "materialRemoved" REAL,
    "workHours" REAL,
    "observations" TEXT,
    "satisfaction" INTEGER,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "tree_pruning_requests_protocolId_fkey" FOREIGN KEY ("protocolId") REFERENCES "protocols_simplified" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "tree_pruning_requests_citizenId_fkey" FOREIGN KEY ("citizenId") REFERENCES "citizens" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "tree_pruning_requests_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_cleaning_schedules" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "tenantId" TEXT NOT NULL,
    "protocolId" TEXT,
    "area" TEXT NOT NULL,
    "cleaningType" TEXT NOT NULL,
    "frequency" TEXT NOT NULL,
    "dayOfWeek" INTEGER,
    "dayOfMonth" INTEGER,
    "startTime" TEXT NOT NULL,
    "duration" INTEGER NOT NULL,
    "estimatedDuration" INTEGER,
    "teamSize" INTEGER NOT NULL,
    "equipment" JSONB,
    "responsibleTeam" TEXT NOT NULL,
    "team" TEXT,
    "vehicle" TEXT,
    "observations" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "lastExecution" DATETIME,
    "nextExecution" DATETIME NOT NULL,
    "executionHistory" JSONB,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "cleaning_schedules_protocolId_fkey" FOREIGN KEY ("protocolId") REFERENCES "protocols_simplified" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "cleaning_schedules_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO "new_cleaning_schedules" ("area", "cleaningType", "createdAt", "dayOfMonth", "dayOfWeek", "duration", "equipment", "estimatedDuration", "executionHistory", "frequency", "id", "isActive", "lastExecution", "nextExecution", "observations", "responsibleTeam", "startTime", "team", "teamSize", "tenantId", "updatedAt", "vehicle") SELECT "area", "cleaningType", "createdAt", "dayOfMonth", "dayOfWeek", "duration", "equipment", "estimatedDuration", "executionHistory", "frequency", "id", "isActive", "lastExecution", "nextExecution", "observations", "responsibleTeam", "startTime", "team", "teamSize", "tenantId", "updatedAt", "vehicle" FROM "cleaning_schedules";
DROP TABLE "cleaning_schedules";
ALTER TABLE "new_cleaning_schedules" RENAME TO "cleaning_schedules";
CREATE TABLE "new_public_problem_reports" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "tenantId" TEXT NOT NULL,
    "protocolId" TEXT,
    "citizenId" TEXT,
    "protocol" TEXT NOT NULL,
    "reporterName" TEXT,
    "reporterPhone" TEXT,
    "reporterEmail" TEXT,
    "problemType" TEXT NOT NULL,
    "title" TEXT,
    "severity" TEXT NOT NULL,
    "riskLevel" TEXT,
    "affectedPeople" INTEGER,
    "description" TEXT NOT NULL,
    "location" TEXT NOT NULL,
    "coordinates" JSONB,
    "landmark" TEXT,
    "photos" JSONB,
    "reportDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" TEXT NOT NULL DEFAULT 'REPORTED',
    "assignedDepartment" TEXT,
    "assignedTeam" TEXT,
    "priority" TEXT NOT NULL DEFAULT 'MEDIUM',
    "estimatedCost" REAL,
    "scheduledDate" DATETIME,
    "completionDate" DATETIME,
    "resolution" TEXT,
    "materials" JSONB,
    "workHours" REAL,
    "isAnonymous" BOOLEAN NOT NULL DEFAULT false,
    "followUp" BOOLEAN NOT NULL DEFAULT false,
    "satisfaction" INTEGER,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "public_problem_reports_protocolId_fkey" FOREIGN KEY ("protocolId") REFERENCES "protocols_simplified" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "public_problem_reports_citizenId_fkey" FOREIGN KEY ("citizenId") REFERENCES "citizens" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "public_problem_reports_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO "new_public_problem_reports" ("affectedPeople", "assignedDepartment", "assignedTeam", "citizenId", "completionDate", "coordinates", "createdAt", "description", "estimatedCost", "followUp", "id", "isAnonymous", "landmark", "location", "materials", "photos", "priority", "problemType", "protocol", "reportDate", "reporterEmail", "reporterName", "reporterPhone", "resolution", "riskLevel", "satisfaction", "scheduledDate", "severity", "status", "tenantId", "title", "updatedAt", "workHours") SELECT "affectedPeople", "assignedDepartment", "assignedTeam", "citizenId", "completionDate", "coordinates", "createdAt", "description", "estimatedCost", "followUp", "id", "isAnonymous", "landmark", "location", "materials", "photos", "priority", "problemType", "protocol", "reportDate", "reporterEmail", "reporterName", "reporterPhone", "resolution", "riskLevel", "satisfaction", "scheduledDate", "severity", "status", "tenantId", "title", "updatedAt", "workHours" FROM "public_problem_reports";
DROP TABLE "public_problem_reports";
ALTER TABLE "new_public_problem_reports" RENAME TO "public_problem_reports";
CREATE UNIQUE INDEX "public_problem_reports_protocol_key" ON "public_problem_reports"("protocol");
CREATE TABLE "new_public_service_requests" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "tenantId" TEXT NOT NULL,
    "protocolId" TEXT,
    "protocol" TEXT NOT NULL,
    "requestorName" TEXT NOT NULL,
    "requestorCpf" TEXT,
    "contact" JSONB NOT NULL,
    "serviceType" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "location" TEXT NOT NULL,
    "coordinates" JSONB,
    "requestDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "preferredDate" DATETIME,
    "urgency" TEXT NOT NULL DEFAULT 'NORMAL',
    "priority" TEXT,
    "photos" JSONB,
    "assignedTeam" TEXT,
    "scheduledDate" DATETIME,
    "expectedDate" DATETIME,
    "completionDate" DATETIME,
    "materials" JSONB,
    "workDetails" TEXT,
    "cost" REAL,
    "estimatedCost" REAL,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "resolution" TEXT,
    "satisfaction" INTEGER,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "public_service_requests_protocolId_fkey" FOREIGN KEY ("protocolId") REFERENCES "protocols_simplified" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "public_service_requests_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO "new_public_service_requests" ("assignedTeam", "category", "completionDate", "contact", "coordinates", "cost", "createdAt", "description", "estimatedCost", "expectedDate", "id", "location", "materials", "photos", "preferredDate", "priority", "protocol", "requestDate", "requestorCpf", "requestorName", "resolution", "satisfaction", "scheduledDate", "serviceType", "status", "tenantId", "updatedAt", "urgency", "workDetails") SELECT "assignedTeam", "category", "completionDate", "contact", "coordinates", "cost", "createdAt", "description", "estimatedCost", "expectedDate", "id", "location", "materials", "photos", "preferredDate", "priority", "protocol", "requestDate", "requestorCpf", "requestorName", "resolution", "satisfaction", "scheduledDate", "serviceType", "status", "tenantId", "updatedAt", "urgency", "workDetails" FROM "public_service_requests";
DROP TABLE "public_service_requests";
ALTER TABLE "new_public_service_requests" RENAME TO "public_service_requests";
CREATE UNIQUE INDEX "public_service_requests_protocol_key" ON "public_service_requests"("protocol");
CREATE TABLE "new_special_collections" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "tenantId" TEXT NOT NULL,
    "protocolId" TEXT,
    "citizenId" TEXT,
    "collectionType" TEXT NOT NULL,
    "requestorName" TEXT NOT NULL,
    "requestorCpf" TEXT,
    "contact" JSONB NOT NULL,
    "address" TEXT NOT NULL,
    "coordinates" JSONB,
    "description" TEXT NOT NULL,
    "estimatedVolume" REAL,
    "quantity" INTEGER,
    "unit" TEXT,
    "photos" JSONB,
    "requestDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "preferredDate" DATETIME,
    "scheduledDate" DATETIME,
    "timeSlot" TEXT,
    "collectionDate" DATETIME,
    "teamAssigned" TEXT,
    "vehicle" TEXT,
    "actualVolume" REAL,
    "destination" TEXT,
    "cost" REAL,
    "status" TEXT NOT NULL DEFAULT 'REQUESTED',
    "observations" TEXT,
    "satisfaction" INTEGER,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "special_collections_protocolId_fkey" FOREIGN KEY ("protocolId") REFERENCES "protocols_simplified" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "special_collections_citizenId_fkey" FOREIGN KEY ("citizenId") REFERENCES "citizens" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "special_collections_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO "new_special_collections" ("actualVolume", "address", "citizenId", "collectionDate", "collectionType", "contact", "coordinates", "cost", "createdAt", "description", "destination", "estimatedVolume", "id", "observations", "photos", "preferredDate", "quantity", "requestDate", "requestorCpf", "requestorName", "satisfaction", "scheduledDate", "status", "teamAssigned", "tenantId", "timeSlot", "unit", "updatedAt", "vehicle") SELECT "actualVolume", "address", "citizenId", "collectionDate", "collectionType", "contact", "coordinates", "cost", "createdAt", "description", "destination", "estimatedVolume", "id", "observations", "photos", "preferredDate", "quantity", "requestDate", "requestorCpf", "requestorName", "satisfaction", "scheduledDate", "status", "teamAssigned", "tenantId", "timeSlot", "unit", "updatedAt", "vehicle" FROM "special_collections";
DROP TABLE "special_collections";
ALTER TABLE "new_special_collections" RENAME TO "special_collections";
CREATE TABLE "new_street_lightings" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "tenantId" TEXT NOT NULL,
    "protocolId" TEXT,
    "pointCode" TEXT NOT NULL,
    "streetName" TEXT NOT NULL,
    "neighborhood" TEXT NOT NULL,
    "coordinates" JSONB NOT NULL,
    "poleType" TEXT NOT NULL,
    "lampType" TEXT NOT NULL,
    "power" INTEGER NOT NULL,
    "height" REAL NOT NULL,
    "installDate" DATETIME,
    "lastMaintenance" DATETIME,
    "nextMaintenance" DATETIME,
    "condition" TEXT NOT NULL DEFAULT 'GOOD',
    "status" TEXT,
    "issues" JSONB,
    "maintenanceHistory" JSONB,
    "energyConsumption" REAL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "photos" JSONB,
    "observations" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "street_lightings_protocolId_fkey" FOREIGN KEY ("protocolId") REFERENCES "protocols_simplified" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "street_lightings_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO "new_street_lightings" ("condition", "coordinates", "createdAt", "energyConsumption", "height", "id", "installDate", "isActive", "issues", "lampType", "lastMaintenance", "maintenanceHistory", "neighborhood", "nextMaintenance", "observations", "photos", "pointCode", "poleType", "power", "status", "streetName", "tenantId", "updatedAt") SELECT "condition", "coordinates", "createdAt", "energyConsumption", "height", "id", "installDate", "isActive", "issues", "lampType", "lastMaintenance", "maintenanceHistory", "neighborhood", "nextMaintenance", "observations", "photos", "pointCode", "poleType", "power", "status", "streetName", "tenantId", "updatedAt" FROM "street_lightings";
DROP TABLE "street_lightings";
ALTER TABLE "new_street_lightings" RENAME TO "street_lightings";
CREATE UNIQUE INDEX "street_lightings_pointCode_key" ON "street_lightings"("pointCode");
CREATE TABLE "new_team_schedules" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "tenantId" TEXT NOT NULL,
    "protocolId" TEXT,
    "teamName" TEXT NOT NULL,
    "teamType" TEXT NOT NULL,
    "shift" TEXT NOT NULL,
    "shiftStart" TEXT,
    "shiftEnd" TEXT,
    "workDays" JSONB NOT NULL,
    "startTime" TEXT NOT NULL,
    "endTime" TEXT NOT NULL,
    "breakTime" JSONB,
    "teamLead" TEXT NOT NULL,
    "members" JSONB NOT NULL,
    "equipment" JSONB,
    "vehicles" JSONB,
    "workAreas" JSONB NOT NULL,
    "dailyTasks" JSONB NOT NULL,
    "weeklyTasks" JSONB,
    "monthlyTasks" JSONB,
    "productivity" JSONB,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "observations" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "team_schedules_protocolId_fkey" FOREIGN KEY ("protocolId") REFERENCES "protocols_simplified" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "team_schedules_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO "new_team_schedules" ("breakTime", "createdAt", "dailyTasks", "endTime", "equipment", "id", "isActive", "members", "monthlyTasks", "observations", "productivity", "shift", "shiftEnd", "shiftStart", "startTime", "teamLead", "teamName", "teamType", "tenantId", "updatedAt", "vehicles", "weeklyTasks", "workAreas", "workDays") SELECT "breakTime", "createdAt", "dailyTasks", "endTime", "equipment", "id", "isActive", "members", "monthlyTasks", "observations", "productivity", "shift", "shiftEnd", "shiftStart", "startTime", "teamLead", "teamName", "teamType", "tenantId", "updatedAt", "vehicles", "weeklyTasks", "workAreas", "workDays" FROM "team_schedules";
DROP TABLE "team_schedules";
ALTER TABLE "new_team_schedules" RENAME TO "team_schedules";
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
