-- CreateTable
CREATE TABLE "tourism_guides" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "tenantId" TEXT NOT NULL,
    "protocolId" TEXT,
    "name" TEXT NOT NULL,
    "cpf" TEXT NOT NULL,
    "rg" TEXT,
    "email" TEXT,
    "phone" TEXT NOT NULL,
    "address" TEXT,
    "birthDate" DATETIME,
    "languages" JSONB NOT NULL,
    "specialties" JSONB,
    "certifications" JSONB,
    "licenseNumber" TEXT,
    "licenseExpiry" DATETIME,
    "registrationDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "experienceYears" INTEGER,
    "bio" TEXT,
    "photo" TEXT,
    "availableSchedule" JSONB,
    "rating" REAL,
    "totalTours" INTEGER NOT NULL DEFAULT 0,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "emergencyContact" JSONB,
    "bankInfo" JSONB,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "tourism_guides_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "tourism_guides_protocolId_fkey" FOREIGN KEY ("protocolId") REFERENCES "protocols_simplified" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "tourism_routes" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "tenantId" TEXT NOT NULL,
    "protocolId" TEXT,
    "name" TEXT NOT NULL,
    "routeType" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "duration" TEXT NOT NULL,
    "difficulty" TEXT NOT NULL,
    "distance" REAL,
    "startPoint" TEXT NOT NULL,
    "endPoint" TEXT NOT NULL,
    "waypoints" JSONB,
    "attractions" JSONB NOT NULL,
    "services" JSONB,
    "bestSeason" JSONB,
    "recommendations" TEXT,
    "warnings" TEXT,
    "accessibility" JSONB,
    "photos" JSONB,
    "mapData" JSONB,
    "estimatedCost" REAL,
    "guideRequired" BOOLEAN NOT NULL DEFAULT false,
    "minimumAge" INTEGER,
    "maxGroupSize" INTEGER,
    "featured" BOOLEAN NOT NULL DEFAULT false,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "rating" REAL,
    "totalViews" INTEGER NOT NULL DEFAULT 0,
    "createdBy" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "tourism_routes_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "tourism_routes_protocolId_fkey" FOREIGN KEY ("protocolId") REFERENCES "protocols_simplified" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "tourism_events" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "tenantId" TEXT NOT NULL,
    "protocolId" TEXT,
    "name" TEXT NOT NULL,
    "eventType" TEXT NOT NULL,
    "category" TEXT,
    "description" TEXT NOT NULL,
    "venue" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "coordinates" JSONB,
    "startDate" DATETIME NOT NULL,
    "endDate" DATETIME NOT NULL,
    "startTime" TEXT,
    "endTime" TEXT,
    "duration" TEXT,
    "organizer" TEXT NOT NULL,
    "organizerContact" JSONB NOT NULL,
    "capacity" INTEGER,
    "registeredCount" INTEGER NOT NULL DEFAULT 0,
    "ticketPrice" REAL,
    "freeEntry" BOOLEAN NOT NULL DEFAULT false,
    "ageRestriction" TEXT,
    "accessibility" JSONB,
    "amenities" JSONB,
    "program" JSONB,
    "speakers" JSONB,
    "sponsors" JSONB,
    "photos" JSONB,
    "promotional" JSONB,
    "status" TEXT NOT NULL DEFAULT 'PLANNED',
    "isPublic" BOOLEAN NOT NULL DEFAULT true,
    "featured" BOOLEAN NOT NULL DEFAULT false,
    "registrationUrl" TEXT,
    "socialMedia" JSONB,
    "tags" JSONB,
    "requirements" TEXT,
    "cancellationInfo" TEXT,
    "createdBy" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "tourism_events_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "tourism_events_protocolId_fkey" FOREIGN KEY ("protocolId") REFERENCES "protocols_simplified" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_local_businesses" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "tenantId" TEXT NOT NULL,
    "protocolId" TEXT,
    "name" TEXT NOT NULL,
    "businessType" TEXT NOT NULL,
    "businessInfo" JSONB,
    "category" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "neighborhood" TEXT,
    "city" TEXT,
    "state" TEXT,
    "coordinates" JSONB,
    "contact" JSONB NOT NULL,
    "openingHours" JSONB NOT NULL,
    "services" JSONB,
    "amenities" JSONB,
    "priceRange" TEXT,
    "rating" REAL,
    "photos" JSONB,
    "owner" TEXT NOT NULL,
    "ownerCpf" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "isTourismPartner" BOOLEAN NOT NULL DEFAULT false,
    "isPartner" BOOLEAN NOT NULL DEFAULT false,
    "certifications" JSONB,
    "protocol" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "local_businesses_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "local_businesses_protocolId_fkey" FOREIGN KEY ("protocolId") REFERENCES "protocols_simplified" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_local_businesses" ("address", "amenities", "businessInfo", "businessType", "category", "certifications", "city", "contact", "coordinates", "createdAt", "description", "id", "isActive", "isPartner", "isTourismPartner", "name", "neighborhood", "openingHours", "owner", "ownerCpf", "photos", "priceRange", "protocol", "rating", "services", "state", "tenantId", "updatedAt") SELECT "address", "amenities", "businessInfo", "businessType", "category", "certifications", "city", "contact", "coordinates", "createdAt", "description", "id", "isActive", "isPartner", "isTourismPartner", "name", "neighborhood", "openingHours", "owner", "ownerCpf", "photos", "priceRange", "protocol", "rating", "services", "state", "tenantId", "updatedAt" FROM "local_businesses";
DROP TABLE "local_businesses";
ALTER TABLE "new_local_businesses" RENAME TO "local_businesses";
CREATE TABLE "new_tourism_attendances" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "tenantId" TEXT NOT NULL,
    "protocolId" TEXT,
    "protocol" TEXT NOT NULL,
    "citizenId" TEXT,
    "visitorName" TEXT NOT NULL,
    "visitorEmail" TEXT,
    "visitorPhone" TEXT,
    "origin" TEXT,
    "serviceType" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "category" TEXT,
    "urgency" TEXT NOT NULL DEFAULT 'NORMAL',
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "assignedAgent" TEXT,
    "resolution" TEXT,
    "satisfaction" INTEGER,
    "followUpDate" DATETIME,
    "touristProfile" JSONB,
    "serviceId" TEXT,
    "source" TEXT NOT NULL DEFAULT 'manual',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "tourism_attendances_citizenId_fkey" FOREIGN KEY ("citizenId") REFERENCES "citizens" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "tourism_attendances_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "tourism_attendances_protocolId_fkey" FOREIGN KEY ("protocolId") REFERENCES "protocols_simplified" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_tourism_attendances" ("assignedAgent", "category", "citizenId", "createdAt", "description", "followUpDate", "id", "origin", "protocol", "resolution", "satisfaction", "serviceId", "serviceType", "source", "status", "subject", "tenantId", "touristProfile", "updatedAt", "urgency", "visitorEmail", "visitorName", "visitorPhone") SELECT "assignedAgent", "category", "citizenId", "createdAt", "description", "followUpDate", "id", "origin", "protocol", "resolution", "satisfaction", "serviceId", "serviceType", "source", "status", "subject", "tenantId", "touristProfile", "updatedAt", "urgency", "visitorEmail", "visitorName", "visitorPhone" FROM "tourism_attendances";
DROP TABLE "tourism_attendances";
ALTER TABLE "new_tourism_attendances" RENAME TO "tourism_attendances";
CREATE UNIQUE INDEX "tourism_attendances_protocol_key" ON "tourism_attendances"("protocol");
CREATE TABLE "new_tourism_programs" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "tenantId" TEXT NOT NULL,
    "protocolId" TEXT,
    "name" TEXT NOT NULL,
    "programType" TEXT NOT NULL,
    "type" TEXT,
    "category" TEXT,
    "description" TEXT NOT NULL,
    "objectives" JSONB NOT NULL,
    "targetAudience" TEXT NOT NULL,
    "startDate" DATETIME NOT NULL,
    "endDate" DATETIME NOT NULL,
    "budget" REAL,
    "coordinator" TEXT NOT NULL,
    "activities" JSONB NOT NULL,
    "participants" JSONB,
    "results" JSONB,
    "status" TEXT NOT NULL DEFAULT 'PLANNED',
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "evaluation" JSONB,
    "photos" JSONB,
    "currentParticipants" INTEGER,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "tourism_programs_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "tourism_programs_protocolId_fkey" FOREIGN KEY ("protocolId") REFERENCES "protocols_simplified" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_tourism_programs" ("activities", "budget", "category", "coordinator", "createdAt", "currentParticipants", "description", "endDate", "evaluation", "id", "isActive", "name", "objectives", "participants", "photos", "programType", "results", "startDate", "status", "targetAudience", "tenantId", "type", "updatedAt") SELECT "activities", "budget", "category", "coordinator", "createdAt", "currentParticipants", "description", "endDate", "evaluation", "id", "isActive", "name", "objectives", "participants", "photos", "programType", "results", "startDate", "status", "targetAudience", "tenantId", "type", "updatedAt" FROM "tourism_programs";
DROP TABLE "tourism_programs";
ALTER TABLE "new_tourism_programs" RENAME TO "tourism_programs";
CREATE TABLE "new_tourist_attractions" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "tenantId" TEXT NOT NULL,
    "protocolId" TEXT,
    "name" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "category" TEXT,
    "description" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "neighborhood" TEXT,
    "coordinates" JSONB,
    "openingHours" TEXT,
    "ticketPrice" REAL,
    "accessibility" JSONB,
    "amenities" JSONB,
    "images" JSONB,
    "rating" REAL,
    "featured" BOOLEAN NOT NULL DEFAULT false,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "freeEntry" BOOLEAN NOT NULL DEFAULT false,
    "protocol" TEXT,
    "city" TEXT,
    "serviceId" TEXT,
    "state" TEXT,
    "facilities" JSONB,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "tourist_attractions_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "tourist_attractions_protocolId_fkey" FOREIGN KEY ("protocolId") REFERENCES "protocols_simplified" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_tourist_attractions" ("accessibility", "address", "amenities", "category", "city", "coordinates", "createdAt", "description", "facilities", "featured", "freeEntry", "id", "images", "isActive", "name", "neighborhood", "openingHours", "protocol", "rating", "serviceId", "state", "tenantId", "ticketPrice", "type", "updatedAt") SELECT "accessibility", "address", "amenities", "category", "city", "coordinates", "createdAt", "description", "facilities", "featured", "freeEntry", "id", "images", "isActive", "name", "neighborhood", "openingHours", "protocol", "rating", "serviceId", "state", "tenantId", "ticketPrice", "type", "updatedAt" FROM "tourist_attractions";
DROP TABLE "tourist_attractions";
ALTER TABLE "new_tourist_attractions" RENAME TO "tourist_attractions";
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

-- CreateIndex
CREATE UNIQUE INDEX "tourism_guides_tenantId_cpf_key" ON "tourism_guides"("tenantId", "cpf");
