/**
 * SEED DE SERVIÇOS INICIAIS - CONSOLIDADO
 *
 * Este arquivo popula o banco de dados com 154 serviços padrão,
 * distribuídos em 13 secretarias municipais.
 *
 * Estrutura:
 * - 10 serviços de Administração Geral
 * - 20 serviços de Saúde
 * - 14 serviços de Educação
 * - 18 serviços de Serviços Públicos
 * - 12 serviços de Assistência Social
 * - 10 serviços de Cultura
 * - 08 serviços de Esporte e Lazer
 * - 14 serviços de Meio Ambiente
 * - 12 serviços de Obras e Infraestrutura
 * - 08 serviços de Planejamento
 * - 10 serviços de Fazenda
 * - 10 serviços de Agricultura
 * - 08 serviços de Turismo
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface ServiceSeedData {
  name: string;
  description: string;
  category: string;
  departmentCode: string; // Código do departamento (ex: 'SAUDE', 'EDUCACAO')
  requiresDocuments: boolean;
  requiredDocuments?: string[];
  estimatedDays: number | null;
  priority: number; // 1-5
  requirements?: string[];
  icon?: string;
  color?: string;
}

// Mapeamento de códigos de departamento (13 secretarias)
const DEPARTMENT_CODES = {
  ADM: 'ADM',
  SAUDE: 'SAUDE',
  EDUCACAO: 'EDUCACAO',
  SERVICOS_PUBLICOS: 'SERVICOS_PUBLICOS',
  ASSISTENCIA_SOCIAL: 'ASSISTENCIA_SOCIAL',
  CULTURA: 'CULTURA',
  ESPORTE_LAZER: 'ESPORTE_LAZER',
  MEIO_AMBIENTE: 'MEIO_AMBIENTE',
  OBRAS_INFRAESTRUTURA: 'OBRAS_INFRAESTRUTURA',
  PLANEJAMENTO: 'PLANEJAMENTO',
  FAZENDA: 'FAZENDA',
  AGRICULTURA: 'AGRICULTURA',
  TURISMO: 'TURISMO',
} as const;

const SERVICES_DATA: ServiceSeedData[] = [
  // ============ ADMINISTRAÇÃO GERAL (10 serviços) ============
  {
    name: 'Registro de Elogio, Sugestão ou Reclamação',
    description: 'Envie elogios, sugestões ou reclamações sobre serviços públicos municipais',
    category: 'Ouvidoria',
    departmentCode: DEPARTMENT_CODES.ADM,
    requiresDocuments: false,
    estimatedDays: 5,
    priority: 3,
    icon: 'MessageCircle',
    color: '#3b82f6',
  },
  {
    name: 'Acompanhamento de Manifestação',
    description: 'Consulte o andamento de sua manifestação na ouvidoria pelo número do protocolo',
    category: 'Ouvidoria',
    departmentCode: DEPARTMENT_CODES.ADM,
    requiresDocuments: true,
    requiredDocuments: ['Número do protocolo'],
    estimatedDays: 0,
    priority: 2,
    icon: 'Search',
    color: '#8b5cf6',
  },
  {
    name: 'Denúncia de Irregularidade',
    description: 'Denuncie irregularidades na administração pública municipal de forma sigilosa',
    category: 'Ouvidoria',
    departmentCode: DEPARTMENT_CODES.ADM,
    requiresDocuments: false,
    estimatedDays: 7,
    priority: 4,
    icon: 'AlertTriangle',
    color: '#ef4444',
  },
  {
    name: 'Consulta de Contracheque',
    description: 'Acesse seus contracheques e histórico de pagamentos como servidor municipal',
    category: 'Recursos Humanos',
    departmentCode: DEPARTMENT_CODES.ADM,
    requiresDocuments: true,
    requiredDocuments: ['Matrícula funcional'],
    estimatedDays: 0,
    priority: 3,
    icon: 'FileText',
    color: '#10b981',
  },
  {
    name: 'Declaração de Vínculo Funcional',
    description: 'Solicite declaração comprovando vínculo empregatício com a prefeitura',
    category: 'Recursos Humanos',
    departmentCode: DEPARTMENT_CODES.ADM,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'Matrícula funcional'],
    estimatedDays: 2,
    priority: 3,
    icon: 'Award',
    color: '#3b82f6',
  },
  {
    name: 'Agendamento de Perícia Médica',
    description: 'Agende perícia médica oficial para atestados e licenças médicas',
    category: 'Recursos Humanos',
    departmentCode: DEPARTMENT_CODES.ADM,
    requiresDocuments: true,
    requiredDocuments: ['Atestado médico', 'Matrícula funcional'],
    estimatedDays: 5,
    priority: 4,
    icon: 'Calendar',
    color: '#f59e0b',
  },
  {
    name: 'Solicitação de Férias',
    description: 'Solicite férias e consulte períodos disponíveis conforme sua escala',
    category: 'Recursos Humanos',
    departmentCode: DEPARTMENT_CODES.ADM,
    requiresDocuments: false,
    estimatedDays: 10,
    priority: 2,
    icon: 'Palmtree',
    color: '#06b6d4',
  },
  {
    name: 'Abertura de Processo Administrativo',
    description: 'Abra processo administrativo para solicitações diversas à prefeitura',
    category: 'Protocolo Geral',
    departmentCode: DEPARTMENT_CODES.ADM,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'Documento relacionado ao pedido'],
    estimatedDays: 3,
    priority: 3,
    icon: 'FileUp',
    color: '#8b5cf6',
  },
  {
    name: 'Consulta de Andamento de Processo',
    description: 'Acompanhe o andamento de processos administrativos pelo número do protocolo',
    category: 'Protocolo Geral',
    departmentCode: DEPARTMENT_CODES.ADM,
    requiresDocuments: true,
    requiredDocuments: ['Número do processo'],
    estimatedDays: 0,
    priority: 2,
    icon: 'Search',
    color: '#10b981',
  },
  {
    name: 'Solicitação de Cópias de Documentos',
    description: 'Solicite cópias autenticadas de documentos arquivados na prefeitura',
    category: 'Protocolo Geral',
    departmentCode: DEPARTMENT_CODES.ADM,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'Número do processo/documento'],
    estimatedDays: 5,
    priority: 2,
    icon: 'Copy',
    color: '#3b82f6',
  },

  // ============ SAÚDE (20 serviços) ============
  {
    name: 'Agendamento de Consulta Geral',
    description: 'Agende consultas médicas em unidades básicas de saúde do município',
    category: 'Consultas Médicas',
    departmentCode: DEPARTMENT_CODES.SAUDE,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'CPF', 'Cartão SUS'],
    estimatedDays: 3,
    priority: 4,
    icon: 'Calendar',
    color: '#10b981',
  },
  {
    name: 'Atendimento de Emergência',
    description: 'Acesso prioritário para casos de emergência médica nas unidades de saúde',
    category: 'Emergência',
    departmentCode: DEPARTMENT_CODES.SAUDE,
    requiresDocuments: true,
    requiredDocuments: ['Documento de identidade'],
    estimatedDays: 0,
    priority: 5,
    icon: 'AlertCircle',
    color: '#ef4444',
  },
  {
    name: 'Consulta Especializada',
    description: 'Agendamento para consultas com médicos especialistas mediante encaminhamento',
    category: 'Especialidades',
    departmentCode: DEPARTMENT_CODES.SAUDE,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'CPF', 'Cartão SUS', 'Encaminhamento médico'],
    estimatedDays: 7,
    priority: 4,
    icon: 'Stethoscope',
    color: '#3b82f6',
  },
  {
    name: 'Agendamento Online de Consultas',
    description: 'Sistema online para agendamento de consultas médicas em unidades de saúde',
    category: 'Agendamentos',
    departmentCode: DEPARTMENT_CODES.SAUDE,
    requiresDocuments: true,
    requiredDocuments: ['Cartão SUS'],
    estimatedDays: 0,
    priority: 5,
    icon: 'Smartphone',
    color: '#8b5cf6',
  },
  {
    name: 'Reagendamento de Consulta',
    description: 'Altere data e horário de consultas já agendadas de forma rápida e fácil',
    category: 'Reagendamentos',
    departmentCode: DEPARTMENT_CODES.SAUDE,
    requiresDocuments: true,
    requiredDocuments: ['Número do agendamento'],
    estimatedDays: 0,
    priority: 3,
    icon: 'RefreshCw',
    color: '#f59e0b',
  },
  {
    name: 'Dispensação de Medicamentos',
    description: 'Retirada de medicamentos na farmácia básica municipal mediante receita médica',
    category: 'Farmácia',
    departmentCode: DEPARTMENT_CODES.SAUDE,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'Receita médica', 'Cartão SUS'],
    estimatedDays: 1,
    priority: 4,
    icon: 'Pill',
    color: '#10b981',
  },
  {
    name: 'Consulta de Estoque de Medicamentos',
    description: 'Verifique a disponibilidade de medicamentos nas farmácias municipais em tempo real',
    category: 'Consultas',
    departmentCode: DEPARTMENT_CODES.SAUDE,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 3,
    icon: 'Package',
    color: '#3b82f6',
  },
  {
    name: 'Inscrição em Campanhas de Vacinação',
    description: 'Cadastre-se nas campanhas de imunização promovidas pelo município',
    category: 'Prevenção',
    departmentCode: DEPARTMENT_CODES.SAUDE,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'CPF', 'Cartão de vacinação'],
    estimatedDays: 2,
    priority: 4,
    icon: 'Syringe',
    color: '#06b6d4',
  },
  {
    name: 'Certificado de Vacinação',
    description: 'Emita certificados e comprovantes de vacinação digital ou físico',
    category: 'Certificados',
    departmentCode: DEPARTMENT_CODES.SAUDE,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'CPF', 'Cartão de vacinação'],
    estimatedDays: 1,
    priority: 4,
    icon: 'FileText',
    color: '#10b981',
  },
  {
    name: 'Inscrição no Programa Hiperdia',
    description: 'Cadastro no programa de acompanhamento de diabetes e hipertensão arterial',
    category: 'Programas de Saúde',
    departmentCode: DEPARTMENT_CODES.SAUDE,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'CPF', 'Cartão SUS', 'Exames recentes'],
    estimatedDays: 3,
    priority: 3,
    icon: 'Heart',
    color: '#ef4444',
  },
  {
    name: 'Acompanhamento Pré-Natal',
    description: 'Cadastro e acompanhamento no programa de saúde para gestantes',
    category: 'Saúde da Mulher',
    departmentCode: DEPARTMENT_CODES.SAUDE,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'CPF', 'Cartão SUS', 'Comprovante de gravidez'],
    estimatedDays: 2,
    priority: 5,
    icon: 'Baby',
    color: '#ec4899',
  },
  {
    name: 'Solicitação de TFD',
    description: 'Tratamento Fora de Domicílio para especialidades não disponíveis no município',
    category: 'TFD',
    departmentCode: DEPARTMENT_CODES.SAUDE,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'CPF', 'Cartão SUS', 'Relatório médico', 'Laudo especializado'],
    estimatedDays: 15,
    priority: 4,
    icon: 'Plane',
    color: '#3b82f6',
  },
  {
    name: 'Acompanhamento de Solicitação TFD',
    description: 'Consulte o andamento de sua solicitação de Tratamento Fora de Domicílio',
    category: 'Consultas',
    departmentCode: DEPARTMENT_CODES.SAUDE,
    requiresDocuments: true,
    requiredDocuments: ['Número do protocolo'],
    estimatedDays: 0,
    priority: 2,
    icon: 'MapPin',
    color: '#8b5cf6',
  },
  {
    name: 'Agendamento de Exames Laboratoriais',
    description: 'Agende exames de sangue, urina e outros laboratoriais na rede municipal',
    category: 'Exames',
    departmentCode: DEPARTMENT_CODES.SAUDE,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'Cartão SUS', 'Solicitação médica'],
    estimatedDays: 5,
    priority: 4,
    icon: 'TestTube',
    color: '#14b8a6',
  },
  {
    name: 'Agendamento de Exames de Imagem',
    description: 'Agende ultrassom, raio-X e outros exames de imagem nas unidades de saúde',
    category: 'Diagnóstico',
    departmentCode: DEPARTMENT_CODES.SAUDE,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'Cartão SUS', 'Solicitação médica'],
    estimatedDays: 7,
    priority: 4,
    icon: 'Scan',
    color: '#3b82f6',
  },
  {
    name: 'Consulta de Resultados de Exames',
    description: 'Acesse os resultados de seus exames laboratoriais e de imagem online',
    category: 'Resultados',
    departmentCode: DEPARTMENT_CODES.SAUDE,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'Número do exame'],
    estimatedDays: 0,
    priority: 3,
    icon: 'FileSearch',
    color: '#10b981',
  },
  {
    name: 'Solicitação de Visita Domiciliar',
    description: 'Agende visita do Agente Comunitário de Saúde em sua residência',
    category: 'Visitas',
    departmentCode: DEPARTMENT_CODES.SAUDE,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'Comprovante de residência'],
    estimatedDays: 7,
    priority: 3,
    icon: 'Home',
    color: '#f59e0b',
  },
  {
    name: 'Cadastro Familiar no PSF',
    description: 'Registre sua família no Programa Saúde da Família para acompanhamento contínuo',
    category: 'Cadastros',
    departmentCode: DEPARTMENT_CODES.SAUDE,
    requiresDocuments: true,
    requiredDocuments: ['RG de todos os membros', 'Comprovante de residência'],
    estimatedDays: 5,
    priority: 3,
    icon: 'Users',
    color: '#8b5cf6',
  },
  {
    name: 'Solicitação de Transporte para Consultas',
    description: 'Solicite transporte municipal para consultas médicas em outras cidades',
    category: 'Transporte',
    departmentCode: DEPARTMENT_CODES.SAUDE,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'Comprovante de agendamento', 'Declaração de carência'],
    estimatedDays: 3,
    priority: 3,
    icon: 'Bus',
    color: '#06b6d4',
  },
  {
    name: 'Transporte para Exames Especializados',
    description: 'Transporte municipal para exames de alta complexidade em outras cidades',
    category: 'Transporte Especializado',
    departmentCode: DEPARTMENT_CODES.SAUDE,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'Solicitação médica', 'Comprovante do exame'],
    estimatedDays: 7,
    priority: 3,
    icon: 'Ambulance',
    color: '#ef4444',
  },

  // ============ EDUCAÇÃO (14 serviços) ============
  {
    name: 'Justificativa de Falta Escolar',
    description: 'Justifique faltas dos estudantes com documentação médica ou declaração',
    category: 'Frequência Escolar',
    departmentCode: DEPARTMENT_CODES.EDUCACAO,
    requiresDocuments: true,
    requiredDocuments: ['Atestado médico', 'RG do responsável'],
    estimatedDays: 2,
    priority: 3,
    icon: 'FileCheck',
    color: '#f59e0b',
  },
  {
    name: 'Consulta de Frequência do Aluno',
    description: 'Acompanhe a frequência escolar do seu filho em tempo real',
    category: 'Consultas Acadêmicas',
    departmentCode: DEPARTMENT_CODES.EDUCACAO,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 2,
    icon: 'Calendar',
    color: '#3b82f6',
  },
  {
    name: 'Matrícula Escolar Online',
    description: 'Realize a matrícula de novos alunos no sistema municipal de ensino',
    category: 'Matrículas',
    departmentCode: DEPARTMENT_CODES.EDUCACAO,
    requiresDocuments: true,
    requiredDocuments: ['Certidão de nascimento', 'RG responsável', 'CPF', 'Comprovante residência', 'Cartão vacinação'],
    estimatedDays: 5,
    priority: 5,
    icon: 'UserPlus',
    color: '#10b981',
  },
  {
    name: 'Transferência Escolar',
    description: 'Solicite transferência entre escolas municipais ou para outras redes',
    category: 'Transferências',
    departmentCode: DEPARTMENT_CODES.EDUCACAO,
    requiresDocuments: true,
    requiredDocuments: ['Histórico escolar', 'Declaração de transferência', 'Justificativa'],
    estimatedDays: 3,
    priority: 4,
    icon: 'RefreshCw',
    color: '#3b82f6',
  },
  {
    name: 'Segunda Via de Histórico Escolar',
    description: 'Solicite segunda via do histórico escolar por perda ou dano',
    category: 'Documentos',
    departmentCode: DEPARTMENT_CODES.EDUCACAO,
    requiresDocuments: true,
    requiredDocuments: ['RG do aluno', 'Comprovante de matrícula'],
    estimatedDays: 7,
    priority: 3,
    icon: 'FileText',
    color: '#8b5cf6',
  },
  {
    name: 'Consulta de Vagas Escolares',
    description: 'Verifique a disponibilidade de vagas nas escolas municipais por região',
    category: 'Informações',
    departmentCode: DEPARTMENT_CODES.EDUCACAO,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 4,
    icon: 'School',
    color: '#10b981',
  },
  {
    name: 'Solicitação de Reunião com Coordenação',
    description: 'Agende reunião com a coordenação pedagógica para tratar assuntos escolares',
    category: 'Atendimento',
    departmentCode: DEPARTMENT_CODES.EDUCACAO,
    requiresDocuments: false,
    estimatedDays: 3,
    priority: 2,
    icon: 'MessageSquare',
    color: '#f59e0b',
  },
  {
    name: 'Solicitação de Transporte Escolar',
    description: 'Solicite vaga no transporte escolar municipal para o seu filho',
    category: 'Transporte',
    departmentCode: DEPARTMENT_CODES.EDUCACAO,
    requiresDocuments: true,
    requiredDocuments: ['Comprovante matrícula', 'Comprovante residência', 'RG responsável'],
    estimatedDays: 10,
    priority: 4,
    icon: 'Bus',
    color: '#f59e0b',
  },
  {
    name: 'Consulta de Rotas de Transporte',
    description: 'Consulte as rotas e horários do transporte escolar por escola ou região',
    category: 'Informações',
    departmentCode: DEPARTMENT_CODES.EDUCACAO,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 2,
    icon: 'Map',
    color: '#06b6d4',
  },
  {
    name: 'Cardápio da Merenda Escolar',
    description: 'Consulte o cardápio semanal/mensal da merenda escolar das escolas municipais',
    category: 'Alimentação',
    departmentCode: DEPARTMENT_CODES.EDUCACAO,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 2,
    icon: 'UtensilsCrossed',
    color: '#10b981',
  },
  {
    name: 'Solicitação de Dieta Especial',
    description: 'Solicite dieta especial para alunos com restrições alimentares ou alergias',
    category: 'Alimentação Especial',
    departmentCode: DEPARTMENT_CODES.EDUCACAO,
    requiresDocuments: true,
    requiredDocuments: ['Laudo médico', 'RG responsável', 'Comprovante matrícula'],
    estimatedDays: 5,
    priority: 4,
    icon: 'Salad',
    color: '#ec4899',
  },
  {
    name: 'Registro de Ocorrência Escolar',
    description: 'Registre ocorrências disciplinares ou pedagógicas para acompanhamento',
    category: 'Disciplina',
    departmentCode: DEPARTMENT_CODES.EDUCACAO,
    requiresDocuments: false,
    estimatedDays: 1,
    priority: 3,
    icon: 'AlertTriangle',
    color: '#ef4444',
  },
  {
    name: 'Acompanhamento Pedagógico',
    description: 'Solicite acompanhamento pedagógico especializado para o aluno',
    category: 'Apoio Pedagógico',
    departmentCode: DEPARTMENT_CODES.EDUCACAO,
    requiresDocuments: true,
    requiredDocuments: ['Relatório escolar', 'RG responsável'],
    estimatedDays: 7,
    priority: 3,
    icon: 'BookOpen',
    color: '#8b5cf6',
  },
  {
    name: 'Consulta do Calendário Escolar',
    description: 'Consulte o calendário oficial das escolas municipais com eventos e feriados',
    category: 'Calendário',
    departmentCode: DEPARTMENT_CODES.EDUCACAO,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 2,
    icon: 'Calendar',
    color: '#3b82f6',
  },

  // ============ SERVIÇOS PÚBLICOS (18 serviços) ============
  {
    name: 'Solicitação de Serviços Urbanos',
    description: 'Solicite serviços de infraestrutura, limpeza e manutenção urbana',
    category: 'Serviços Urbanos',
    departmentCode: DEPARTMENT_CODES.SERVICOS_PUBLICOS,
    requiresDocuments: false,
    estimatedDays: 5,
    priority: 3,
    icon: 'Wrench',
    color: '#f59e0b',
  },
  {
    name: 'Acompanhamento de Protocolo Urbano',
    description: 'Consulte o andamento de solicitações de serviços urbanos pelo número do protocolo',
    category: 'Consultas',
    departmentCode: DEPARTMENT_CODES.SERVICOS_PUBLICOS,
    requiresDocuments: true,
    requiredDocuments: ['Número do protocolo'],
    estimatedDays: 0,
    priority: 2,
    icon: 'Search',
    color: '#3b82f6',
  },
  {
    name: 'Consulta de Cronograma de Coleta',
    description: 'Verifique os dias e horários de coleta de lixo em sua rua',
    category: 'Informações',
    departmentCode: DEPARTMENT_CODES.SERVICOS_PUBLICOS,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 3,
    icon: 'Trash2',
    color: '#10b981',
  },
  {
    name: 'Denúncia de Descarte Irregular',
    description: 'Denuncie descarte irregular de lixo, entulho e outros resíduos',
    category: 'Denúncias',
    departmentCode: DEPARTMENT_CODES.SERVICOS_PUBLICOS,
    requiresDocuments: false,
    estimatedDays: 1,
    priority: 4,
    icon: 'AlertOctagon',
    color: '#ef4444',
  },
  {
    name: 'Solicitação de Reparo de Iluminação',
    description: 'Reporte problemas na iluminação pública para manutenção',
    category: 'Manutenção',
    departmentCode: DEPARTMENT_CODES.SERVICOS_PUBLICOS,
    requiresDocuments: false,
    estimatedDays: 5,
    priority: 3,
    icon: 'Lightbulb',
    color: '#f59e0b',
  },
  {
    name: 'Solicitação de Nova Iluminação',
    description: 'Solicite instalação de novos pontos de iluminação pública',
    category: 'Instalação',
    departmentCode: DEPARTMENT_CODES.SERVICOS_PUBLICOS,
    requiresDocuments: false,
    estimatedDays: 15,
    priority: 2,
    icon: 'Zap',
    color: '#3b82f6',
  },
  {
    name: 'Agendamento de Coleta de Resíduos Especiais',
    description: 'Agende coleta de eletrônicos, óleo, baterias e medicamentos vencidos',
    category: 'Coleta Especial',
    departmentCode: DEPARTMENT_CODES.SERVICOS_PUBLICOS,
    requiresDocuments: false,
    estimatedDays: 7,
    priority: 3,
    icon: 'Recycle',
    color: '#10b981',
  },
  {
    name: 'Certificado de Destinação de Resíduos',
    description: 'Obtenha certificado de destinação ambientalmente correta de resíduos',
    category: 'Certificados',
    departmentCode: DEPARTMENT_CODES.SERVICOS_PUBLICOS,
    requiresDocuments: true,
    requiredDocuments: ['Comprovante de entrega', 'Tipo de resíduo'],
    estimatedDays: 3,
    priority: 2,
    icon: 'Award',
    color: '#10b981',
  },
  {
    name: 'Consulta de Pontos de Coleta',
    description: 'Encontre pontos de coleta de resíduos especiais próximos à sua região',
    category: 'Informações',
    departmentCode: DEPARTMENT_CODES.SERVICOS_PUBLICOS,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 2,
    icon: 'MapPin',
    color: '#06b6d4',
  },
  {
    name: 'Relatório de Problema Urbano com Foto',
    description: 'Reporte problemas de infraestrutura urbana anexando fotos para agilizar',
    category: 'Denúncias',
    departmentCode: DEPARTMENT_CODES.SERVICOS_PUBLICOS,
    requiresDocuments: false,
    estimatedDays: 5,
    priority: 3,
    icon: 'Camera',
    color: '#8b5cf6',
  },
  {
    name: 'Solicitação de Vistoria Técnica',
    description: 'Solicite vistoria técnica especializada para problemas urbanos complexos',
    category: 'Vistorias',
    departmentCode: DEPARTMENT_CODES.SERVICOS_PUBLICOS,
    requiresDocuments: false,
    estimatedDays: 3,
    priority: 3,
    icon: 'ClipboardCheck',
    color: '#f59e0b',
  },
  {
    name: 'Agendamento de Serviços Urbanos',
    description: 'Agende serviços de limpeza, manutenção e infraestrutura programados',
    category: 'Agendamentos',
    departmentCode: DEPARTMENT_CODES.SERVICOS_PUBLICOS,
    requiresDocuments: false,
    estimatedDays: 3,
    priority: 3,
    icon: 'CalendarClock',
    color: '#3b82f6',
  },
  {
    name: 'Acompanhamento de Equipes',
    description: 'Consulte o cronograma e localização das equipes de trabalho em tempo real',
    category: 'Informações',
    departmentCode: DEPARTMENT_CODES.SERVICOS_PUBLICOS,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 2,
    icon: 'Users',
    color: '#10b981',
  },
  {
    name: 'Solicitação de Serviço Emergencial',
    description: 'Solicite atendimento emergencial para problemas urbanos urgentes',
    category: 'Emergência',
    departmentCode: DEPARTMENT_CODES.SERVICOS_PUBLICOS,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 5,
    icon: 'Siren',
    color: '#ef4444',
  },
  {
    name: 'Consulta de Serviços Urbanos',
    description: 'Consulte status e histórico de todos os serviços urbanos solicitados',
    category: 'Relatórios',
    departmentCode: DEPARTMENT_CODES.SERVICOS_PUBLICOS,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 2,
    icon: 'BarChart',
    color: '#8b5cf6',
  },
  {
    name: 'Relatório de Serviços Públicos',
    description: 'Solicite relatórios detalhados sobre serviços executados em sua região',
    category: 'Relatórios',
    departmentCode: DEPARTMENT_CODES.SERVICOS_PUBLICOS,
    requiresDocuments: false,
    estimatedDays: 5,
    priority: 2,
    icon: 'FileBarChart',
    color: '#3b82f6',
  },
  {
    name: 'Solicitação de Limpeza Especial',
    description: 'Solicite limpeza especial para eventos, terrenos ou situações específicas',
    category: 'Limpeza Especial',
    departmentCode: DEPARTMENT_CODES.SERVICOS_PUBLICOS,
    requiresDocuments: false,
    estimatedDays: 3,
    priority: 2,
    icon: 'Sparkles',
    color: '#06b6d4',
  },
  {
    name: 'Agendamento Integrado de Serviços',
    description: 'Agende múltiplos serviços urbanos de forma integrada e otimizada',
    category: 'Agendamentos',
    departmentCode: DEPARTMENT_CODES.SERVICOS_PUBLICOS,
    requiresDocuments: false,
    estimatedDays: 3,
    priority: 2,
    icon: 'ListTodo',
    color: '#8b5cf6',
  },

  // ============ ASSISTÊNCIA SOCIAL (12 serviços) ============
  {
    name: 'Cadastro no CadÚnico',
    description: 'Cadastre-se no Cadastro Único para acessar programas sociais do governo',
    category: 'Programas Sociais',
    departmentCode: DEPARTMENT_CODES.ASSISTENCIA_SOCIAL,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'CPF', 'Comprovante de residência', 'Comprovante de renda'],
    estimatedDays: 7,
    priority: 5,
    icon: 'Users',
    color: '#10b981',
  },
  {
    name: 'Inscrição no Bolsa Família',
    description: 'Solicite inscrição no programa Bolsa Família para famílias em vulnerabilidade',
    category: 'Programas Sociais',
    departmentCode: DEPARTMENT_CODES.ASSISTENCIA_SOCIAL,
    requiresDocuments: true,
    requiredDocuments: ['Cadastro CadÚnico', 'RG', 'CPF', 'Comprovante de renda'],
    estimatedDays: 15,
    priority: 5,
    icon: 'DollarSign',
    color: '#10b981',
  },
  {
    name: 'Benefício de Prestação Continuada (BPC)',
    description: 'Solicite BPC para idosos acima de 65 anos ou pessoas com deficiência',
    category: 'Programas Sociais',
    departmentCode: DEPARTMENT_CODES.ASSISTENCIA_SOCIAL,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'CPF', 'Laudo médico (se aplicável)', 'Comprovante de renda familiar'],
    estimatedDays: 30,
    priority: 5,
    icon: 'Heart',
    color: '#ef4444',
  },
  {
    name: 'Cartão Alimentação Municipal',
    description: 'Solicite cartão alimentação para famílias em situação de insegurança alimentar',
    category: 'Programas Sociais',
    departmentCode: DEPARTMENT_CODES.ASSISTENCIA_SOCIAL,
    requiresDocuments: true,
    requiredDocuments: ['Cadastro CadÚnico', 'Comprovante de residência'],
    estimatedDays: 10,
    priority: 4,
    icon: 'ShoppingCart',
    color: '#f59e0b',
  },
  {
    name: 'Solicitação de Abrigo Temporário',
    description: 'Solicite acolhimento temporário em situação de emergência ou vulnerabilidade',
    category: 'Acolhimento',
    departmentCode: DEPARTMENT_CODES.ASSISTENCIA_SOCIAL,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'Relatório social'],
    estimatedDays: 1,
    priority: 5,
    icon: 'Home',
    color: '#3b82f6',
  },
  {
    name: 'Encaminhamento para Casa de Passagem',
    description: 'Encaminhamento para casa de passagem em situação de rua ou vulnerabilidade',
    category: 'Acolhimento',
    departmentCode: DEPARTMENT_CODES.ASSISTENCIA_SOCIAL,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 5,
    icon: 'Building',
    color: '#8b5cf6',
  },
  {
    name: 'Acolhimento Institucional para Crianças',
    description: 'Acolhimento institucional para crianças e adolescentes em situação de risco',
    category: 'Acolhimento',
    departmentCode: DEPARTMENT_CODES.ASSISTENCIA_SOCIAL,
    requiresDocuments: true,
    requiredDocuments: ['Relatório do Conselho Tutelar', 'Documentos da criança'],
    estimatedDays: 1,
    priority: 5,
    icon: 'Baby',
    color: '#ec4899',
  },
  {
    name: 'Atendimento Psicossocial',
    description: 'Agende atendimento com psicólogo e assistente social da rede municipal',
    category: 'Atendimento Especializado',
    departmentCode: DEPARTMENT_CODES.ASSISTENCIA_SOCIAL,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'Encaminhamento (se houver)'],
    estimatedDays: 7,
    priority: 4,
    icon: 'Brain',
    color: '#8b5cf6',
  },
  {
    name: 'Assistência Jurídica Gratuita',
    description: 'Solicite assistência jurídica gratuita para questões cíveis e familiares',
    category: 'Atendimento Especializado',
    departmentCode: DEPARTMENT_CODES.ASSISTENCIA_SOCIAL,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'CPF', 'Comprovante de renda', 'Documentos do caso'],
    estimatedDays: 10,
    priority: 4,
    icon: 'Scale',
    color: '#3b82f6',
  },
  {
    name: 'Centro de Referência da Mulher (CRAM)',
    description: 'Atendimento especializado para mulheres em situação de violência doméstica',
    category: 'Atendimento Especializado',
    departmentCode: DEPARTMENT_CODES.ASSISTENCIA_SOCIAL,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 5,
    icon: 'Shield',
    color: '#ec4899',
  },
  {
    name: 'Atendimento no CRAS',
    description: 'Agende atendimento no Centro de Referência de Assistência Social',
    category: 'Atendimento Especializado',
    departmentCode: DEPARTMENT_CODES.ASSISTENCIA_SOCIAL,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'Comprovante de residência'],
    estimatedDays: 5,
    priority: 4,
    icon: 'MapPin',
    color: '#10b981',
  },
  {
    name: 'Atendimento no CREAS',
    description: 'Atendimento no Centro de Referência Especializado de Assistência Social',
    category: 'Atendimento Especializado',
    departmentCode: DEPARTMENT_CODES.ASSISTENCIA_SOCIAL,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'Relatório de encaminhamento'],
    estimatedDays: 7,
    priority: 5,
    icon: 'Briefcase',
    color: '#ef4444',
  },

  // ============ CULTURA (10 serviços) ============
  {
    name: 'Reserva de Espaços Culturais',
    description: 'Reserve teatros, centros culturais e auditórios municipais para eventos',
    category: 'Eventos e Espaços',
    departmentCode: DEPARTMENT_CODES.CULTURA,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'Projeto do evento', 'Comprovante de responsabilidade'],
    estimatedDays: 15,
    priority: 3,
    icon: 'Theater',
    color: '#8b5cf6',
  },
  {
    name: 'Inscrição em Oficinas Culturais',
    description: 'Inscreva-se em oficinas de música, dança, teatro e artes plásticas',
    category: 'Eventos e Espaços',
    departmentCode: DEPARTMENT_CODES.CULTURA,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'Comprovante de residência'],
    estimatedDays: 5,
    priority: 4,
    icon: 'Palette',
    color: '#ec4899',
  },
  {
    name: 'Consulta Agenda Cultural',
    description: 'Consulte a agenda de eventos culturais do município',
    category: 'Eventos e Espaços',
    departmentCode: DEPARTMENT_CODES.CULTURA,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 2,
    icon: 'Calendar',
    color: '#3b82f6',
  },
  {
    name: 'Solicitação de Apoio para Eventos',
    description: 'Solicite apoio da prefeitura para realização de eventos culturais',
    category: 'Eventos e Espaços',
    departmentCode: DEPARTMENT_CODES.CULTURA,
    requiresDocuments: true,
    requiredDocuments: ['Projeto do evento', 'Orçamento', 'Cronograma'],
    estimatedDays: 20,
    priority: 3,
    icon: 'PartyPopper',
    color: '#f59e0b',
  },
  {
    name: 'Lei de Incentivo à Cultura',
    description: 'Cadastre projetos culturais na lei municipal de incentivo à cultura',
    category: 'Incentivo Cultural',
    departmentCode: DEPARTMENT_CODES.CULTURA,
    requiresDocuments: true,
    requiredDocuments: ['Projeto cultural completo', 'Orçamento detalhado', 'Portfólio'],
    estimatedDays: 30,
    priority: 3,
    icon: 'Coins',
    color: '#10b981',
  },
  {
    name: 'Edital de Fomento Cultural',
    description: 'Participe de editais de fomento para projetos culturais do município',
    category: 'Incentivo Cultural',
    departmentCode: DEPARTMENT_CODES.CULTURA,
    requiresDocuments: true,
    requiredDocuments: ['Projeto cultural', 'Documentos do proponente', 'Contrapartidas'],
    estimatedDays: 45,
    priority: 3,
    icon: 'FileText',
    color: '#3b82f6',
  },
  {
    name: 'Cadastro de Artistas Locais',
    description: 'Cadastre-se no banco de artistas e produtores culturais do município',
    category: 'Incentivo Cultural',
    departmentCode: DEPARTMENT_CODES.CULTURA,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'CPF', 'Portfólio artístico', 'Currículo'],
    estimatedDays: 7,
    priority: 3,
    icon: 'Music',
    color: '#8b5cf6',
  },
  {
    name: 'Visitação a Museus Municipais',
    description: 'Agende visitação guiada aos museus e espaços históricos do município',
    category: 'Patrimônio',
    departmentCode: DEPARTMENT_CODES.CULTURA,
    requiresDocuments: false,
    estimatedDays: 3,
    priority: 2,
    icon: 'Landmark',
    color: '#06b6d4',
  },
  {
    name: 'Tombamento de Patrimônio Histórico',
    description: 'Solicite tombamento de imóveis ou bens de valor histórico e cultural',
    category: 'Patrimônio',
    departmentCode: DEPARTMENT_CODES.CULTURA,
    requiresDocuments: true,
    requiredDocuments: ['Documentação do bem', 'Justificativa histórica', 'Fotos'],
    estimatedDays: 60,
    priority: 2,
    icon: 'Building2',
    color: '#ef4444',
  },
  {
    name: 'Acesso ao Arquivo Histórico Municipal',
    description: 'Consulte documentos históricos e acervos do arquivo público municipal',
    category: 'Patrimônio',
    departmentCode: DEPARTMENT_CODES.CULTURA,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'Termo de responsabilidade'],
    estimatedDays: 2,
    priority: 2,
    icon: 'Archive',
    color: '#8b5cf6',
  },

  // ============ ESPORTE E LAZER (8 serviços) ============
  {
    name: 'Reserva de Quadras e Ginásios',
    description: 'Reserve quadras esportivas e ginásios municipais para prática esportiva',
    category: 'Instalações Esportivas',
    departmentCode: DEPARTMENT_CODES.ESPORTE_LAZER,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'Termo de responsabilidade'],
    estimatedDays: 3,
    priority: 3,
    icon: 'Dumbbell',
    color: '#f59e0b',
  },
  {
    name: 'Inscrição em Escolinhas Esportivas',
    description: 'Inscreva crianças e adolescentes em escolinhas de futebol, vôlei, basquete e outras modalidades',
    category: 'Instalações Esportivas',
    departmentCode: DEPARTMENT_CODES.ESPORTE_LAZER,
    requiresDocuments: true,
    requiredDocuments: ['Certidão de nascimento', 'RG responsável', 'Atestado médico'],
    estimatedDays: 7,
    priority: 4,
    icon: 'Trophy',
    color: '#10b981',
  },
  {
    name: 'Aluguel de Campos de Futebol',
    description: 'Alugue campos de futebol municipais para peladas e treinos',
    category: 'Instalações Esportivas',
    departmentCode: DEPARTMENT_CODES.ESPORTE_LAZER,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'Termo de responsabilidade'],
    estimatedDays: 2,
    priority: 2,
    icon: 'CircleDot',
    color: '#06b6d4',
  },
  {
    name: 'Inscrição em Campeonatos Municipais',
    description: 'Inscreva times e atletas em campeonatos esportivos promovidos pela prefeitura',
    category: 'Eventos',
    departmentCode: DEPARTMENT_CODES.ESPORTE_LAZER,
    requiresDocuments: true,
    requiredDocuments: ['Ficha de inscrição', 'Documentos dos atletas', 'Atestados médicos'],
    estimatedDays: 10,
    priority: 3,
    icon: 'Medal',
    color: '#f59e0b',
  },
  {
    name: 'Consulta Calendário Esportivo',
    description: 'Consulte calendário de eventos e campeonatos esportivos do município',
    category: 'Eventos',
    departmentCode: DEPARTMENT_CODES.ESPORTE_LAZER,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 2,
    icon: 'Calendar',
    color: '#3b82f6',
  },
  {
    name: 'Solicitação de Apoio para Eventos Esportivos',
    description: 'Solicite apoio da prefeitura para organização de eventos esportivos',
    category: 'Eventos',
    departmentCode: DEPARTMENT_CODES.ESPORTE_LAZER,
    requiresDocuments: true,
    requiredDocuments: ['Projeto do evento', 'Orçamento', 'Cronograma'],
    estimatedDays: 20,
    priority: 3,
    icon: 'Flag',
    color: '#10b981',
  },
  {
    name: 'Academia ao Ar Livre - Solicitação de Manutenção',
    description: 'Reporte problemas e solicite manutenção de academias ao ar livre',
    category: 'Programas',
    departmentCode: DEPARTMENT_CODES.ESPORTE_LAZER,
    requiresDocuments: false,
    estimatedDays: 7,
    priority: 3,
    icon: 'Wrench',
    color: '#ef4444',
  },
  {
    name: 'Programa Atleta do Futuro',
    description: 'Inscreva-se no programa de formação e apoio a jovens atletas',
    category: 'Programas',
    departmentCode: DEPARTMENT_CODES.ESPORTE_LAZER,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'Atestado médico', 'Comprovante escolar'],
    estimatedDays: 15,
    priority: 4,
    icon: 'Star',
    color: '#8b5cf6',
  },

  // ============ MEIO AMBIENTE (14 serviços) ============
  {
    name: 'Licença Ambiental Simplificada',
    description: 'Solicite licença ambiental para atividades de baixo impacto ambiental',
    category: 'Licenciamento',
    departmentCode: DEPARTMENT_CODES.MEIO_AMBIENTE,
    requiresDocuments: true,
    requiredDocuments: ['Projeto técnico', 'Documentos do requerente', 'ART do responsável técnico'],
    estimatedDays: 30,
    priority: 3,
    icon: 'FileCheck',
    color: '#10b981',
  },
  {
    name: 'Autorização de Poda de Árvores',
    description: 'Solicite autorização para poda de árvores em propriedade privada',
    category: 'Licenciamento',
    departmentCode: DEPARTMENT_CODES.MEIO_AMBIENTE,
    requiresDocuments: true,
    requiredDocuments: ['Comprovante de propriedade', 'Fotos da árvore', 'Justificativa'],
    estimatedDays: 10,
    priority: 3,
    icon: 'Trees',
    color: '#10b981',
  },
  {
    name: 'Autorização de Supressão Vegetal',
    description: 'Solicite autorização para supressão de vegetação em área privada',
    category: 'Licenciamento',
    departmentCode: DEPARTMENT_CODES.MEIO_AMBIENTE,
    requiresDocuments: true,
    requiredDocuments: ['Projeto de supressão', 'Matrícula do imóvel', 'Estudo ambiental'],
    estimatedDays: 45,
    priority: 3,
    icon: 'Axe',
    color: '#ef4444',
  },
  {
    name: 'Licença para Eventos em Áreas Verdes',
    description: 'Solicite autorização para eventos em parques e áreas verdes municipais',
    category: 'Licenciamento',
    departmentCode: DEPARTMENT_CODES.MEIO_AMBIENTE,
    requiresDocuments: true,
    requiredDocuments: ['Projeto do evento', 'Plano de gerenciamento de resíduos'],
    estimatedDays: 15,
    priority: 3,
    icon: 'PartyPopper',
    color: '#06b6d4',
  },
  {
    name: 'Denúncia de Crime Ambiental',
    description: 'Denuncie crimes ambientais como desmatamento, poluição e caça ilegal',
    category: 'Fiscalização',
    departmentCode: DEPARTMENT_CODES.MEIO_AMBIENTE,
    requiresDocuments: false,
    estimatedDays: 2,
    priority: 5,
    icon: 'AlertTriangle',
    color: '#ef4444',
  },
  {
    name: 'Denúncia de Maus-tratos a Animais',
    description: 'Denuncie maus-tratos, abandono e abuso de animais domésticos e silvestres',
    category: 'Fiscalização',
    departmentCode: DEPARTMENT_CODES.MEIO_AMBIENTE,
    requiresDocuments: false,
    estimatedDays: 1,
    priority: 5,
    icon: 'Dog',
    color: '#ec4899',
  },
  {
    name: 'Denúncia de Poluição Sonora',
    description: 'Denuncie poluição sonora de estabelecimentos comerciais ou residências',
    category: 'Fiscalização',
    departmentCode: DEPARTMENT_CODES.MEIO_AMBIENTE,
    requiresDocuments: false,
    estimatedDays: 3,
    priority: 4,
    icon: 'Volume2',
    color: '#f59e0b',
  },
  {
    name: 'Doação de Mudas de Árvores',
    description: 'Solicite mudas de árvores nativas para plantio em propriedade privada',
    category: 'Programas Ambientais',
    departmentCode: DEPARTMENT_CODES.MEIO_AMBIENTE,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'Comprovante de residência', 'Termo de compromisso'],
    estimatedDays: 10,
    priority: 3,
    icon: 'Sprout',
    color: '#10b981',
  },
  {
    name: 'Cadastro em Programas de Reciclagem',
    description: 'Cadastre-se em programas de coleta seletiva e reciclagem do município',
    category: 'Programas Ambientais',
    departmentCode: DEPARTMENT_CODES.MEIO_AMBIENTE,
    requiresDocuments: true,
    requiredDocuments: ['Comprovante de residência'],
    estimatedDays: 5,
    priority: 3,
    icon: 'Recycle',
    color: '#10b981',
  },
  {
    name: 'Coleta de Óleo de Cozinha',
    description: 'Agende coleta de óleo de cozinha usado para reciclagem',
    category: 'Programas Ambientais',
    departmentCode: DEPARTMENT_CODES.MEIO_AMBIENTE,
    requiresDocuments: false,
    estimatedDays: 7,
    priority: 2,
    icon: 'Droplet',
    color: '#f59e0b',
  },
  {
    name: 'Educação Ambiental nas Escolas',
    description: 'Solicite palestras e atividades de educação ambiental para escolas',
    category: 'Programas Ambientais',
    departmentCode: DEPARTMENT_CODES.MEIO_AMBIENTE,
    requiresDocuments: true,
    requiredDocuments: ['Ofício da escola', 'Cronograma sugerido'],
    estimatedDays: 15,
    priority: 3,
    icon: 'GraduationCap',
    color: '#3b82f6',
  },
  {
    name: 'Ecoponto - Descarte de Entulho',
    description: 'Solicite acesso a ecopontos para descarte correto de entulho e resíduos de construção',
    category: 'Gestão de Resíduos',
    departmentCode: DEPARTMENT_CODES.MEIO_AMBIENTE,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'Comprovante de residência'],
    estimatedDays: 3,
    priority: 3,
    icon: 'Trash',
    color: '#8b5cf6',
  },
  {
    name: 'Agendamento de Poda Municipal',
    description: 'Solicite poda de árvores em vias públicas pela equipe municipal',
    category: 'Gestão de Resíduos',
    departmentCode: DEPARTMENT_CODES.MEIO_AMBIENTE,
    requiresDocuments: false,
    estimatedDays: 15,
    priority: 3,
    icon: 'Scissors',
    color: '#10b981',
  },
  {
    name: 'Remoção de Animais Silvestres',
    description: 'Solicite remoção segura de animais silvestres em área urbana',
    category: 'Gestão de Resíduos',
    departmentCode: DEPARTMENT_CODES.MEIO_AMBIENTE,
    requiresDocuments: false,
    estimatedDays: 1,
    priority: 4,
    icon: 'Bug',
    color: '#ef4444',
  },

  // ============ OBRAS E INFRAESTRUTURA (12 serviços) ============
  {
    name: 'Solicitação de Tapa-Buraco',
    description: 'Solicite reparo de buracos e defeitos no asfalto de vias públicas',
    category: 'Obras Públicas',
    departmentCode: DEPARTMENT_CODES.OBRAS_INFRAESTRUTURA,
    requiresDocuments: false,
    estimatedDays: 10,
    priority: 4,
    icon: 'Construction',
    color: '#f59e0b',
  },
  {
    name: 'Reparo de Calçadas Públicas',
    description: 'Solicite reparo de calçadas danificadas em vias públicas',
    category: 'Obras Públicas',
    departmentCode: DEPARTMENT_CODES.OBRAS_INFRAESTRUTURA,
    requiresDocuments: false,
    estimatedDays: 15,
    priority: 3,
    icon: 'HardHat',
    color: '#06b6d4',
  },
  {
    name: 'Manutenção de Pontes e Viadutos',
    description: 'Reporte problemas em pontes e viadutos municipais',
    category: 'Obras Públicas',
    departmentCode: DEPARTMENT_CODES.OBRAS_INFRAESTRUTURA,
    requiresDocuments: false,
    estimatedDays: 20,
    priority: 5,
    icon: 'Bridge',
    color: '#ef4444',
  },
  {
    name: 'Solicitação de Drenagem Pluvial',
    description: 'Solicite instalação ou manutenção de sistema de drenagem de águas pluviais',
    category: 'Obras Públicas',
    departmentCode: DEPARTMENT_CODES.OBRAS_INFRAESTRUTURA,
    requiresDocuments: true,
    requiredDocuments: ['Endereço completo', 'Fotos do problema'],
    estimatedDays: 30,
    priority: 4,
    icon: 'Waves',
    color: '#3b82f6',
  },
  {
    name: 'Alvará de Construção',
    description: 'Solicite alvará para construção, reforma ou ampliação de edificações',
    category: 'Fiscalização de Obras',
    departmentCode: DEPARTMENT_CODES.OBRAS_INFRAESTRUTURA,
    requiresDocuments: true,
    requiredDocuments: ['Projeto aprovado', 'ART', 'Matrícula do imóvel', 'IPTU'],
    estimatedDays: 20,
    priority: 4,
    icon: 'FileText',
    color: '#10b981',
  },
  {
    name: 'Habite-se',
    description: 'Solicite certidão de conclusão de obra (habite-se) após finalização da construção',
    category: 'Fiscalização de Obras',
    departmentCode: DEPARTMENT_CODES.OBRAS_INFRAESTRUTURA,
    requiresDocuments: true,
    requiredDocuments: ['Alvará de construção', 'Projeto as-built', 'ART de conclusão'],
    estimatedDays: 30,
    priority: 4,
    icon: 'CheckCircle',
    color: '#10b981',
  },
  {
    name: 'Fiscalização de Obra Irregular',
    description: 'Denuncie obras irregulares sem alvará ou em desacordo com o projeto',
    category: 'Fiscalização de Obras',
    departmentCode: DEPARTMENT_CODES.OBRAS_INFRAESTRUTURA,
    requiresDocuments: false,
    estimatedDays: 5,
    priority: 4,
    icon: 'ShieldAlert',
    color: '#ef4444',
  },
  {
    name: 'Solicitação de Meio-Fio',
    description: 'Solicite instalação de meio-fio em vias públicas não contempladas',
    category: 'Infraestrutura Urbana',
    departmentCode: DEPARTMENT_CODES.OBRAS_INFRAESTRUTURA,
    requiresDocuments: true,
    requiredDocuments: ['Endereço', 'Abaixo-assinado dos moradores'],
    estimatedDays: 60,
    priority: 2,
    icon: 'Square',
    color: '#8b5cf6',
  },
  {
    name: 'Pavimentação de Ruas',
    description: 'Solicite pavimentação asfáltica de ruas sem pavimento',
    category: 'Infraestrutura Urbana',
    departmentCode: DEPARTMENT_CODES.OBRAS_INFRAESTRUTURA,
    requiresDocuments: true,
    requiredDocuments: ['Abaixo-assinado', 'Justificativa'],
    estimatedDays: 90,
    priority: 3,
    icon: 'Road',
    color: '#3b82f6',
  },
  {
    name: 'Construção de Rede de Esgoto',
    description: 'Solicite ampliação da rede de esgoto para áreas não atendidas',
    category: 'Infraestrutura Urbana',
    departmentCode: DEPARTMENT_CODES.OBRAS_INFRAESTRUTURA,
    requiresDocuments: true,
    requiredDocuments: ['Abaixo-assinado', 'Mapa da região'],
    estimatedDays: 120,
    priority: 5,
    icon: 'Droplets',
    color: '#06b6d4',
  },
  {
    name: 'Ampliação de Rede de Água',
    description: 'Solicite ampliação da rede de abastecimento de água potável',
    category: 'Infraestrutura Urbana',
    departmentCode: DEPARTMENT_CODES.OBRAS_INFRAESTRUTURA,
    requiresDocuments: true,
    requiredDocuments: ['Abaixo-assinado', 'Justificativa técnica'],
    estimatedDays: 120,
    priority: 5,
    icon: 'Droplet',
    color: '#3b82f6',
  },
  {
    name: 'Instalação de Sinalização Viária',
    description: 'Solicite instalação de placas, faixas de pedestres e semáforos',
    category: 'Infraestrutura Urbana',
    departmentCode: DEPARTMENT_CODES.OBRAS_INFRAESTRUTURA,
    requiresDocuments: true,
    requiredDocuments: ['Justificativa', 'Fotos do local'],
    estimatedDays: 30,
    priority: 4,
    icon: 'OctagonAlert',
    color: '#ef4444',
  },

  // ============ PLANEJAMENTO (8 serviços) ============
  {
    name: 'Consulta ao Plano Diretor',
    description: 'Consulte o Plano Diretor Municipal e diretrizes de uso do solo',
    category: 'Planejamento Urbano',
    departmentCode: DEPARTMENT_CODES.PLANEJAMENTO,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 3,
    icon: 'Map',
    color: '#3b82f6',
  },
  {
    name: 'Certidão de Uso do Solo',
    description: 'Solicite certidão de uso e ocupação do solo para imóveis',
    category: 'Planejamento Urbano',
    departmentCode: DEPARTMENT_CODES.PLANEJAMENTO,
    requiresDocuments: true,
    requiredDocuments: ['Matrícula do imóvel', 'RG do proprietário'],
    estimatedDays: 10,
    priority: 4,
    icon: 'FileText',
    color: '#10b981',
  },
  {
    name: 'Análise de Zoneamento',
    description: 'Consulte zoneamento e parâmetros urbanísticos de áreas específicas',
    category: 'Planejamento Urbano',
    departmentCode: DEPARTMENT_CODES.PLANEJAMENTO,
    requiresDocuments: true,
    requiredDocuments: ['Endereço ou coordenadas'],
    estimatedDays: 7,
    priority: 3,
    icon: 'MapPin',
    color: '#8b5cf6',
  },
  {
    name: 'Consulta de Loteamento',
    description: 'Consulte informações sobre loteamentos aprovados e em aprovação',
    category: 'Planejamento Urbano',
    departmentCode: DEPARTMENT_CODES.PLANEJAMENTO,
    requiresDocuments: false,
    estimatedDays: 5,
    priority: 2,
    icon: 'Grid3x3',
    color: '#06b6d4',
  },
  {
    name: 'Consulta Projetos em Andamento',
    description: 'Consulte projetos de infraestrutura e obras em andamento no município',
    category: 'Projetos',
    departmentCode: DEPARTMENT_CODES.PLANEJAMENTO,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 2,
    icon: 'FolderKanban',
    color: '#f59e0b',
  },
  {
    name: 'Participação em Audiências Públicas',
    description: 'Inscreva-se para participar de audiências públicas sobre projetos urbanos',
    category: 'Projetos',
    departmentCode: DEPARTMENT_CODES.PLANEJAMENTO,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'Email para confirmação'],
    estimatedDays: 3,
    priority: 3,
    icon: 'Users',
    color: '#3b82f6',
  },
  {
    name: 'Mapas e Plantas da Cidade',
    description: 'Solicite mapas oficiais, plantas cadastrais e cartografia municipal',
    category: 'Informações',
    departmentCode: DEPARTMENT_CODES.PLANEJAMENTO,
    requiresDocuments: true,
    requiredDocuments: ['Justificativa', 'RG'],
    estimatedDays: 7,
    priority: 2,
    icon: 'Map',
    color: '#10b981',
  },
  {
    name: 'Estatísticas Municipais',
    description: 'Acesse dados estatísticos sobre população, economia e infraestrutura do município',
    category: 'Informações',
    departmentCode: DEPARTMENT_CODES.PLANEJAMENTO,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 2,
    icon: 'BarChart3',
    color: '#8b5cf6',
  },

  // ============ FAZENDA (10 serviços) ============
  {
    name: 'Emissão de Segunda Via de IPTU',
    description: 'Emita segunda via de carnê de IPTU por perda ou não recebimento',
    category: 'IPTU',
    departmentCode: DEPARTMENT_CODES.FAZENDA,
    requiresDocuments: true,
    requiredDocuments: ['Inscrição do imóvel ou endereço completo'],
    estimatedDays: 2,
    priority: 4,
    icon: 'FileText',
    color: '#3b82f6',
  },
  {
    name: 'Parcelamento de IPTU',
    description: 'Solicite parcelamento de IPTU em atraso ou do exercício corrente',
    category: 'IPTU',
    departmentCode: DEPARTMENT_CODES.FAZENDA,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'CPF', 'Carnê de IPTU'],
    estimatedDays: 5,
    priority: 4,
    icon: 'CreditCard',
    color: '#f59e0b',
  },
  {
    name: 'Isenção de IPTU (Idosos/Deficientes)',
    description: 'Solicite isenção de IPTU para idosos, aposentados ou pessoas com deficiência',
    category: 'IPTU',
    departmentCode: DEPARTMENT_CODES.FAZENDA,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'CPF', 'Comprovante de propriedade', 'Laudo médico (se aplicável)', 'Comprovante de renda'],
    estimatedDays: 15,
    priority: 4,
    icon: 'BadgePercent',
    color: '#10b981',
  },
  {
    name: 'Atualização Cadastral de Imóvel',
    description: 'Atualize dados cadastrais de imóveis no sistema da fazenda municipal',
    category: 'IPTU',
    departmentCode: DEPARTMENT_CODES.FAZENDA,
    requiresDocuments: true,
    requiredDocuments: ['Matrícula do imóvel', 'RG do proprietário', 'Documentos atualizados'],
    estimatedDays: 10,
    priority: 3,
    icon: 'RefreshCw',
    color: '#8b5cf6',
  },
  {
    name: 'Emissão de Nota Fiscal de Serviço',
    description: 'Emita nota fiscal eletrônica de serviços prestados (NFSe)',
    category: 'ISS e Taxas',
    departmentCode: DEPARTMENT_CODES.FAZENDA,
    requiresDocuments: true,
    requiredDocuments: ['Cadastro de prestador ativo', 'Dados do tomador'],
    estimatedDays: 0,
    priority: 5,
    icon: 'Receipt',
    color: '#10b981',
  },
  {
    name: 'Cadastro de Prestador de Serviços',
    description: 'Cadastre-se como prestador de serviços para emissão de NFSe',
    category: 'ISS e Taxas',
    departmentCode: DEPARTMENT_CODES.FAZENDA,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'CPF', 'Inscrição municipal (se houver)', 'Comprovante de endereço'],
    estimatedDays: 7,
    priority: 4,
    icon: 'UserPlus',
    color: '#3b82f6',
  },
  {
    name: 'Consulta de Débitos Municipais',
    description: 'Consulte débitos de IPTU, ISS, taxas e multas municipais',
    category: 'ISS e Taxas',
    departmentCode: DEPARTMENT_CODES.FAZENDA,
    requiresDocuments: true,
    requiredDocuments: ['CPF ou CNPJ'],
    estimatedDays: 0,
    priority: 3,
    icon: 'Search',
    color: '#ef4444',
  },
  {
    name: 'Certidão Negativa de Débitos (CND)',
    description: 'Emita Certidão Negativa de Débitos municipais para licitações e contratos',
    category: 'Certidões',
    departmentCode: DEPARTMENT_CODES.FAZENDA,
    requiresDocuments: true,
    requiredDocuments: ['CPF ou CNPJ', 'Inscrição municipal'],
    estimatedDays: 3,
    priority: 5,
    icon: 'FileCheck',
    color: '#10b981',
  },
  {
    name: 'Certidão de Valor Venal',
    description: 'Solicite certidão de valor venal de imóvel para fins diversos',
    category: 'Certidões',
    departmentCode: DEPARTMENT_CODES.FAZENDA,
    requiresDocuments: true,
    requiredDocuments: ['Inscrição do imóvel', 'RG do proprietário'],
    estimatedDays: 5,
    priority: 3,
    icon: 'DollarSign',
    color: '#f59e0b',
  },
  {
    name: 'Certidão de Cadastro Imobiliário',
    description: 'Emita certidão com informações cadastrais do imóvel no município',
    category: 'Certidões',
    departmentCode: DEPARTMENT_CODES.FAZENDA,
    requiresDocuments: true,
    requiredDocuments: ['Inscrição do imóvel', 'RG do solicitante'],
    estimatedDays: 5,
    priority: 3,
    icon: 'Home',
    color: '#3b82f6',
  },

  // ============ AGRICULTURA (10 serviços) ============
  {
    name: 'Cadastro de Produtor Rural',
    description: 'Cadastre-se como produtor rural para acessar programas e benefícios',
    category: 'Apoio ao Produtor',
    departmentCode: DEPARTMENT_CODES.AGRICULTURA,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'CPF', 'Comprovante de propriedade ou posse', 'CAR (se houver)'],
    estimatedDays: 10,
    priority: 4,
    icon: 'UserPlus',
    color: '#10b981',
  },
  {
    name: 'Solicitação de Trator e Máquinas Agrícolas',
    description: 'Solicite empréstimo de trator e máquinas agrícolas da prefeitura',
    category: 'Apoio ao Produtor',
    departmentCode: DEPARTMENT_CODES.AGRICULTURA,
    requiresDocuments: true,
    requiredDocuments: ['Cadastro de produtor rural', 'Comprovante de propriedade'],
    estimatedDays: 15,
    priority: 4,
    icon: 'Tractor',
    color: '#f59e0b',
  },
  {
    name: 'Análise de Solo',
    description: 'Solicite análise de solo para orientação de plantio e correção',
    category: 'Apoio ao Produtor',
    departmentCode: DEPARTMENT_CODES.AGRICULTURA,
    requiresDocuments: true,
    requiredDocuments: ['Cadastro de produtor rural', 'Amostra de solo'],
    estimatedDays: 20,
    priority: 3,
    icon: 'TestTube',
    color: '#8b5cf6',
  },
  {
    name: 'Orientação Técnica Agrícola',
    description: 'Solicite visita técnica de agrônomo para orientação agrícola',
    category: 'Apoio ao Produtor',
    departmentCode: DEPARTMENT_CODES.AGRICULTURA,
    requiresDocuments: true,
    requiredDocuments: ['Cadastro de produtor rural'],
    estimatedDays: 10,
    priority: 3,
    icon: 'Leaf',
    color: '#10b981',
  },
  {
    name: 'Programa de Distribuição de Sementes',
    description: 'Solicite sementes subsidiadas pela prefeitura para plantio',
    category: 'Fomento',
    departmentCode: DEPARTMENT_CODES.AGRICULTURA,
    requiresDocuments: true,
    requiredDocuments: ['Cadastro de produtor rural', 'Projeto de plantio'],
    estimatedDays: 15,
    priority: 4,
    icon: 'Sprout',
    color: '#10b981',
  },
  {
    name: 'Programa de Aquisição de Alimentos (PAA)',
    description: 'Cadastre-se no PAA para venda de produtos à prefeitura',
    category: 'Fomento',
    departmentCode: DEPARTMENT_CODES.AGRICULTURA,
    requiresDocuments: true,
    requiredDocuments: ['DAP', 'Projeto de venda', 'Nota do produtor'],
    estimatedDays: 30,
    priority: 4,
    icon: 'ShoppingBag',
    color: '#3b82f6',
  },
  {
    name: 'Feira do Produtor - Reserva de Banca',
    description: 'Reserve banca na feira do produtor para venda direta ao consumidor',
    category: 'Fomento',
    departmentCode: DEPARTMENT_CODES.AGRICULTURA,
    requiresDocuments: true,
    requiredDocuments: ['Cadastro de produtor rural', 'Alvará sanitário'],
    estimatedDays: 7,
    priority: 3,
    icon: 'Store',
    color: '#f59e0b',
  },
  {
    name: 'Inspeção Sanitária de Produtos',
    description: 'Solicite inspeção sanitária de produtos de origem animal e vegetal',
    category: 'Fiscalização',
    departmentCode: DEPARTMENT_CODES.AGRICULTURA,
    requiresDocuments: true,
    requiredDocuments: ['Cadastro de produtor rural', 'Documentação do produto'],
    estimatedDays: 10,
    priority: 4,
    icon: 'ClipboardCheck',
    color: '#ef4444',
  },
  {
    name: 'Certificação de Origem Animal',
    description: 'Solicite certificação para produtos de origem animal (GTA)',
    category: 'Fiscalização',
    departmentCode: DEPARTMENT_CODES.AGRICULTURA,
    requiresDocuments: true,
    requiredDocuments: ['Cadastro de produtor rural', 'Atestado sanitário'],
    estimatedDays: 5,
    priority: 4,
    icon: 'Award',
    color: '#10b981',
  },
  {
    name: 'Registro de Agrotóxicos',
    description: 'Registre a compra e uso de agrotóxicos conforme legislação municipal',
    category: 'Fiscalização',
    departmentCode: DEPARTMENT_CODES.AGRICULTURA,
    requiresDocuments: true,
    requiredDocuments: ['Receituário agronômico', 'Nota fiscal'],
    estimatedDays: 3,
    priority: 3,
    icon: 'Flask',
    color: '#ef4444',
  },

  // ============ TURISMO (8 serviços) ============
  {
    name: 'Guia Turístico Digital',
    description: 'Acesse o guia turístico digital com pontos turísticos e informações',
    category: 'Informações Turísticas',
    departmentCode: DEPARTMENT_CODES.TURISMO,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 2,
    icon: 'Map',
    color: '#3b82f6',
  },
  {
    name: 'Roteiros Turísticos',
    description: 'Consulte roteiros turísticos sugeridos para conhecer o município',
    category: 'Informações Turísticas',
    departmentCode: DEPARTMENT_CODES.TURISMO,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 2,
    icon: 'Route',
    color: '#10b981',
  },
  {
    name: 'Calendário de Eventos Turísticos',
    description: 'Consulte calendário de festas, feiras e eventos turísticos',
    category: 'Informações Turísticas',
    departmentCode: DEPARTMENT_CODES.TURISMO,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 2,
    icon: 'Calendar',
    color: '#f59e0b',
  },
  {
    name: 'Cadastro de Guias de Turismo',
    description: 'Cadastre-se como guia de turismo oficial do município',
    category: 'Cadastros',
    departmentCode: DEPARTMENT_CODES.TURISMO,
    requiresDocuments: true,
    requiredDocuments: ['RG', 'CPF', 'Certificado de guia', 'Cadastur'],
    estimatedDays: 15,
    priority: 3,
    icon: 'UserCheck',
    color: '#3b82f6',
  },
  {
    name: 'Cadastro de Estabelecimentos Turísticos',
    description: 'Cadastre hotéis, pousadas e restaurantes no portal turístico',
    category: 'Cadastros',
    departmentCode: DEPARTMENT_CODES.TURISMO,
    requiresDocuments: true,
    requiredDocuments: ['CNPJ', 'Alvará de funcionamento', 'Fotos do estabelecimento'],
    estimatedDays: 10,
    priority: 3,
    icon: 'Building',
    color: '#10b981',
  },
  {
    name: 'Selo de Qualidade Turística',
    description: 'Solicite certificação de qualidade para estabelecimentos turísticos',
    category: 'Cadastros',
    departmentCode: DEPARTMENT_CODES.TURISMO,
    requiresDocuments: true,
    requiredDocuments: ['Cadastro do estabelecimento', 'Checklist de conformidade'],
    estimatedDays: 30,
    priority: 3,
    icon: 'Award',
    color: '#f59e0b',
  },
  {
    name: 'Apoio a Eventos Turísticos',
    description: 'Solicite apoio da prefeitura para eventos que promovam o turismo local',
    category: 'Apoio',
    departmentCode: DEPARTMENT_CODES.TURISMO,
    requiresDocuments: true,
    requiredDocuments: ['Projeto do evento', 'Orçamento', 'Contrapartidas'],
    estimatedDays: 30,
    priority: 3,
    icon: 'PartyPopper',
    color: '#ec4899',
  },
  {
    name: 'Material de Divulgação Turística',
    description: 'Solicite folders, mapas e materiais de divulgação turística do município',
    category: 'Apoio',
    departmentCode: DEPARTMENT_CODES.TURISMO,
    requiresDocuments: true,
    requiredDocuments: ['Justificativa', 'Quantidade solicitada'],
    estimatedDays: 10,
    priority: 2,
    icon: 'BookOpen',
    color: '#8b5cf6',
  },
];

/**
 * Seed dos serviços iniciais para um tenant específico
 */
export async function seedInitialServices(tenantId: string) {
  console.log(`\n📋 Populando serviços para tenant ${tenantId}...`);

  try {
    // Buscar departamentos do tenant
    const departments = await prisma.department.findMany({
      where: { tenantId, isActive: true },
      select: { id: true, code: true, name: true },
    });

    if (departments.length === 0) {
      console.warn('   ⚠️  Nenhum departamento encontrado. Crie departamentos antes de popular serviços.');
      return { created: 0, skipped: SERVICES_DATA.length };
    }

    console.log(`   📁 ${departments.length} departamentos encontrados`);

    // Criar mapa de código -> departmentId
    const departmentMap = new Map<string, string>();
    departments.forEach((dept) => {
      if (dept.code) {
        departmentMap.set(dept.code, dept.id);
      }
    });

    let created = 0;
    let skipped = 0;
    let errors = 0;

    for (const serviceData of SERVICES_DATA) {
      try {
        // Buscar departmentId pelo código
        const departmentId = departmentMap.get(serviceData.departmentCode);

        if (!departmentId) {
          console.warn(`   ⚠️  Departamento ${serviceData.departmentCode} não encontrado. Pulando "${serviceData.name}"`);
          skipped++;
          continue;
        }

        // Verificar se serviço já existe
        const existing = await prisma.serviceSimplified.findFirst({
          where: {
            name: serviceData.name,
            tenantId,
          },
        });

        if (existing) {
          skipped++;
          continue;
        }

        // Criar serviço
        await prisma.serviceSimplified.create({
          data: {
            name: serviceData.name,
            description: serviceData.description,
            category: serviceData.category,
            tenantId,
            departmentId,
            requiresDocuments: serviceData.requiresDocuments,
            requiredDocuments: serviceData.requiredDocuments || [],
            estimatedDays: serviceData.estimatedDays,
            priority: serviceData.priority,
            // requirements removido - campo não existe mais no schema
            icon: serviceData.icon,
            color: serviceData.color,
            isActive: true,
            serviceType: 'COM_DADOS', // Campo obrigatório adicionado
          },
        });

        created++;
      } catch (error) {
        console.error(`   ❌ Erro ao criar serviço "${serviceData.name}":`, error);
        errors++;
      }
    }

    console.log(`   ✅ ${created} serviços criados`);
    if (skipped > 0) console.log(`   ⏭️  ${skipped} serviços já existentes (pulados)`);
    if (errors > 0) console.log(`   ❌ ${errors} erros`);

    return { created, skipped, errors };
  } catch (error) {
    console.error('   ❌ Erro ao popular serviços:', error);
    throw error;
  }
}

/**
 * Execução standalone para testes
 */
async function main() {
  const DEMO_TENANT_ID = 'demo';

  await seedInitialServices(DEMO_TENANT_ID);

  console.log('\n✅ Seed de serviços concluído!');
}

// Executar se chamado diretamente
if (require.main === module) {
  main()
    .then(async () => {
      await prisma.$disconnect();
    })
    .catch(async (e) => {
      console.error(e);
      await prisma.$disconnect();
      process.exit(1);
    });
}
