/**
 * SEED DE SERVIÇOS V2 - PARTE 2
 * Secretarias restantes: Agricultura, Cultura, Esportes, Habitação,
 * Meio Ambiente, Obras, Planejamento, Segurança, Serviços Públicos, Turismo
 */

export const SERVICES_V2_PART2 = [
  // ========================================
  // SECRETARIA DE AGRICULTURA (6 serviços)
  // ========================================
  {
    name: 'Atendimentos de Agricultura',
    description: 'Registrar atendimentos gerais da secretaria de agricultura',
    category: 'Atendimento',
    departmentCode: 'AGRICULTURA',
    serviceType: 'COM_DADOS',
    moduleType: 'ATENDIMENTOS_AGRICULTURA',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoAtendimento', type: 'select', label: 'Tipo de Atendimento', required: true, options: ['Assistência Técnica', 'Cadastro', 'Informação', 'Curso'] },
        { id: 'assunto', type: 'textarea', label: 'Assunto', required: true },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 5,
    priority: 3,
    icon: 'Tractor',
    color: '#10b981',
  },
  {
    name: 'Cadastro de Produtor',
    description: 'Cadastrar produtor rural no município',
    category: 'Cadastro',
    departmentCode: 'AGRICULTURA',
    serviceType: 'COM_DADOS',
    moduleType: 'CADASTRO_PRODUTOR',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'nomeProdutor', type: 'text', label: 'Nome do Produtor', required: true },
        { id: 'cpf', type: 'text', label: 'CPF', required: true },
        { id: 'propriedade', type: 'text', label: 'Nome da Propriedade', required: true },
        { id: 'area', type: 'number', label: 'Área Total (hectares)', required: true },
        { id: 'tipoProducao', type: 'select', label: 'Tipo de Produção', required: true, options: ['Agricultura', 'Pecuária', 'Agricultura e Pecuária', 'Agroindústria'] },
        { id: 'principaisCulturas', type: 'textarea', label: 'Principais Culturas/Criações', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['RG', 'CPF', 'Comprovante de posse da terra', 'CAR (se possuir)'],
    estimatedDays: 10,
    priority: 4,
    icon: 'UserPlus',
    color: '#22c55e',
  },
  {
    name: 'Assistência Técnica',
    description: 'Solicitar visita técnica e orientação agrícola',
    category: 'Assistência',
    departmentCode: 'AGRICULTURA',
    serviceType: 'COM_DADOS',
    moduleType: 'ASSISTENCIA_TECNICA',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoAssistencia', type: 'select', label: 'Tipo de Assistência', required: true, options: ['Análise de Solo', 'Controle de Pragas', 'Manejo de Culturas', 'Irrigação', 'Pecuária', 'Agroindústria'] },
        { id: 'cultura', type: 'text', label: 'Cultura/Criação', required: true },
        { id: 'problema', type: 'textarea', label: 'Descrição do Problema/Necessidade', required: true },
        { id: 'urgente', type: 'select', label: 'Urgente?', required: true, options: ['Sim', 'Não'] },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 7,
    priority: 4,
    icon: 'Wrench',
    color: '#f59e0b',
  },
  {
    name: 'Inscrição em Curso Rural',
    description: 'Inscrever-se em cursos e capacitações rurais',
    category: 'Capacitação',
    departmentCode: 'AGRICULTURA',
    serviceType: 'COM_DADOS',
    moduleType: 'INSCRICAO_CURSO_RURAL',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'nomeCurso', type: 'select', label: 'Curso', required: true, options: ['Agricultura Orgânica', 'Apicultura', 'Piscicultura', 'Manejo de Pastagens', 'Fabricação de Queijos', 'Outros'] },
        { id: 'nomeParticipante', type: 'text', label: 'Nome do Participante', required: true },
        { id: 'cpf', type: 'text', label: 'CPF', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
        { id: 'experiencia', type: 'textarea', label: 'Experiência na Área', required: false },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['RG', 'CPF'],
    estimatedDays: 5,
    priority: 3,
    icon: 'GraduationCap',
    color: '#8b5cf6',
  },
  {
    name: 'Inscrição em Programa Rural',
    description: 'Inscrever-se em programas de fomento agrícola',
    category: 'Programas',
    departmentCode: 'AGRICULTURA',
    serviceType: 'COM_DADOS',
    moduleType: 'INSCRICAO_PROGRAMA_RURAL',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'programa', type: 'select', label: 'Programa', required: true, options: ['Distribuição de Sementes', 'Distribuição de Mudas', 'Incentivo à Mecanização', 'Crédito Rural', 'PAA', 'PNAE'] },
        { id: 'producao', type: 'textarea', label: 'Produção Atual', required: true },
        { id: 'projeto', type: 'textarea', label: 'Projeto/Proposta', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['Cadastro de produtor', 'Projeto técnico (se aplicável)'],
    estimatedDays: 15,
    priority: 4,
    icon: 'Sprout',
    color: '#22c55e',
  },
  {
    name: 'Cadastro de Propriedade Rural',
    description: 'Cadastrar propriedade rural no sistema',
    category: 'Cadastro',
    departmentCode: 'AGRICULTURA',
    serviceType: 'COM_DADOS',
    moduleType: 'CADASTRO_PROPRIEDADE_RURAL',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'nomePropriedade', type: 'text', label: 'Nome da Propriedade', required: true },
        { id: 'areaTotal', type: 'number', label: 'Área Total (hectares)', required: true },
        { id: 'areaAgricola', type: 'number', label: 'Área Agrícola (hectares)', required: true },
        { id: 'localizacao', type: 'text', label: 'Localização', required: true },
        { id: 'car', type: 'text', label: 'CAR', required: false },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['Escritura ou documento de posse', 'CAR'],
    estimatedDays: 10,
    priority: 3,
    icon: 'MapPin',
    color: '#10b981',
  },

  // ========================================
  // SECRETARIA DE CULTURA (9 serviços)
  // ========================================
  {
    name: 'Atendimentos de Cultura',
    description: 'Registrar atendimentos gerais da secretaria de cultura',
    category: 'Atendimento',
    departmentCode: 'CULTURA',
    serviceType: 'COM_DADOS',
    moduleType: 'ATENDIMENTOS_CULTURA',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'assunto', type: 'textarea', label: 'Assunto', required: true },
        { id: 'tipo', type: 'select', label: 'Tipo', required: true, options: ['Informação', 'Reserva', 'Inscrição', 'Reclamação'] },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 5,
    priority: 3,
    icon: 'Palette',
    color: '#8b5cf6',
  },
  {
    name: 'Reserva de Espaço Cultural',
    description: 'Reservar espaços culturais (teatro, auditório, centro cultural)',
    category: 'Reserva',
    departmentCode: 'CULTURA',
    serviceType: 'COM_DADOS',
    moduleType: 'RESERVA_ESPACO_CULTURAL',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'espaco', type: 'select', label: 'Espaço', required: true, options: ['Teatro Municipal', 'Auditório', 'Centro Cultural', 'Biblioteca', 'Galeria de Arte'] },
        { id: 'dataEvento', type: 'date', label: 'Data do Evento', required: true },
        { id: 'horario', type: 'text', label: 'Horário', required: true },
        { id: 'tipoEvento', type: 'select', label: 'Tipo de Evento', required: true, options: ['Apresentação', 'Palestra', 'Workshop', 'Exposição', 'Ensaio'] },
        { id: 'descricaoEvento', type: 'textarea', label: 'Descrição do Evento', required: true },
        { id: 'publicoEstimado', type: 'number', label: 'Público Estimado', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['Projeto do evento', 'RG e CPF do responsável'],
    estimatedDays: 10,
    priority: 3,
    icon: 'Theater',
    color: '#ec4899',
  },
  {
    name: 'Inscrição em Oficina Cultural',
    description: 'Inscrever-se em oficinas culturais (música, dança, teatro, artes)',
    category: 'Oficinas',
    departmentCode: 'CULTURA',
    serviceType: 'COM_DADOS',
    moduleType: 'INSCRICAO_OFICINA_CULTURAL',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'oficina', type: 'select', label: 'Oficina', required: true, options: ['Violão', 'Teatro', 'Dança', 'Pintura', 'Artesanato', 'Canto'] },
        { id: 'nomeParticipante', type: 'text', label: 'Nome do Participante', required: true },
        { id: 'idade', type: 'number', label: 'Idade', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
        { id: 'experiencia', type: 'textarea', label: 'Experiência Prévia', required: false },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['RG', 'CPF'],
    estimatedDays: 5,
    priority: 3,
    icon: 'Music',
    color: '#f59e0b',
  },
  {
    name: 'Cadastro de Grupo Artístico',
    description: 'Cadastrar grupo artístico local',
    category: 'Cadastro',
    departmentCode: 'CULTURA',
    serviceType: 'COM_DADOS',
    moduleType: 'CADASTRO_GRUPO_ARTISTICO',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'nomeGrupo', type: 'text', label: 'Nome do Grupo', required: true },
        { id: 'tipo', type: 'select', label: 'Tipo', required: true, options: ['Musical', 'Teatro', 'Dança', 'Folclórico', 'Outros'] },
        { id: 'responsavel', type: 'text', label: 'Responsável', required: true },
        { id: 'numeroIntegrantes', type: 'number', label: 'Número de Integrantes', required: true },
        { id: 'descricao', type: 'textarea', label: 'Descrição do Grupo', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['RG e CPF do responsável', 'Lista de integrantes'],
    estimatedDays: 7,
    priority: 3,
    icon: 'Users',
    color: '#8b5cf6',
  },
  {
    name: 'Projeto Cultural',
    description: 'Submeter projeto para lei de incentivo ou edital cultural',
    category: 'Projetos',
    departmentCode: 'CULTURA',
    serviceType: 'COM_DADOS',
    moduleType: 'PROJETO_CULTURAL',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tituloProjeto', type: 'text', label: 'Título do Projeto', required: true },
        { id: 'tipo', type: 'select', label: 'Tipo', required: true, options: ['Música', 'Teatro', 'Dança', 'Artes Visuais', 'Literatura', 'Audiovisual'] },
        { id: 'resumo', type: 'textarea', label: 'Resumo do Projeto', required: true },
        { id: 'orcamento', type: 'number', label: 'Orçamento Estimado (R$)', required: true },
        { id: 'proponente', type: 'text', label: 'Proponente', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['Projeto completo', 'Orçamento detalhado', 'RG e CPF'],
    estimatedDays: 30,
    priority: 3,
    icon: 'FileText',
    color: '#3b82f6',
  },
  {
    name: 'Submissão de Projeto Cultural',
    description: 'Submeter projeto para análise e aprovação',
    category: 'Projetos',
    departmentCode: 'CULTURA',
    serviceType: 'COM_DADOS',
    moduleType: 'SUBMISSAO_PROJETO_CULTURAL',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'edital', type: 'text', label: 'Edital/Programa', required: true },
        { id: 'arquivo', type: 'text', label: 'Link do Projeto', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['Projeto completo'],
    estimatedDays: 45,
    priority: 3,
    icon: 'Upload',
    color: '#10b981',
  },
  {
    name: 'Cadastro de Evento Cultural',
    description: 'Cadastrar evento cultural no calendário municipal',
    category: 'Eventos',
    departmentCode: 'CULTURA',
    serviceType: 'COM_DADOS',
    moduleType: 'CADASTRO_EVENTO_CULTURAL',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'nomeEvento', type: 'text', label: 'Nome do Evento', required: true },
        { id: 'tipo', type: 'select', label: 'Tipo', required: true, options: ['Show', 'Peça', 'Festival', 'Exposição', 'Workshop', 'Palestra'] },
        { id: 'dataEvento', type: 'date', label: 'Data', required: true },
        { id: 'local', type: 'text', label: 'Local', required: true },
        { id: 'descricao', type: 'textarea', label: 'Descrição', required: true },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 5,
    priority: 3,
    icon: 'CalendarDays',
    color: '#f59e0b',
  },
  {
    name: 'Registro de Manifestação Cultural',
    description: 'Registrar manifestação cultural local (patrimônio imaterial)',
    category: 'Patrimônio',
    departmentCode: 'CULTURA',
    serviceType: 'COM_DADOS',
    moduleType: 'REGISTRO_MANIFESTACAO_CULTURAL',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'nomeManifestacao', type: 'text', label: 'Nome da Manifestação', required: true },
        { id: 'tipo', type: 'select', label: 'Tipo', required: true, options: ['Festa Popular', 'Dança Tradicional', 'Artesanato', 'Culinária', 'Música Tradicional'] },
        { id: 'historico', type: 'textarea', label: 'Histórico', required: true },
        { id: 'relevancia', type: 'textarea', label: 'Relevância Cultural', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['Documentação histórica', 'Fotos/vídeos'],
    estimatedDays: 30,
    priority: 2,
    icon: 'Landmark',
    color: '#8b5cf6',
  },
  {
    name: 'Agenda de Eventos Culturais',
    description: 'Consultar agenda cultural do município',
    category: 'Informação',
    departmentCode: 'CULTURA',
    serviceType: 'INFORMATIVO',
    moduleType: null,
    formSchema: null,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 1,
    icon: 'CalendarDays',
    color: '#ec4899',
  },

  // Continua com mais secretarias...
  // Por brevidade, vou incluir apenas alguns exemplos
];

export default SERVICES_V2_PART2;
