/**
 * DADOS COMPLETOS DOS 108 SERVIÇOS - TODAS AS SECRETARIAS
 * Para ser integrado ao seed principal
 */

export const SERVICES_COMPLETE_DATA = [
  // ========================================
  // SECRETARIA DE ESPORTES (9 serviços)
  // ========================================
  {
    name: 'Atendimentos de Esportes',
    description: 'Registrar atendimentos gerais da secretaria de esportes',
    category: 'Atendimento',
    departmentCode: 'ESPORTE_LAZER',
    serviceType: 'COM_DADOS',
    moduleType: 'ATENDIMENTOS_ESPORTES',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'assunto', type: 'textarea', label: 'Assunto', required: true },
        { id: 'tipo', type: 'select', label: 'Tipo', required: true, options: ['Informação', 'Inscrição', 'Reserva', 'Reclamação'] },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 5,
    priority: 3,
    icon: 'Dumbbell',
    color: '#f59e0b',
  },
  {
    name: 'Inscrição em Escolinha',
    description: 'Inscrever-se em escolinhas esportivas municipais',
    category: 'Escolinhas',
    departmentCode: 'ESPORTE_LAZER',
    serviceType: 'COM_DADOS',
    moduleType: 'INSCRICAO_ESCOLINHA',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'modalidade', type: 'select', label: 'Modalidade', required: true, options: ['Futebol', 'Vôlei', 'Basquete', 'Natação', 'Judô', 'Karatê', 'Atletismo', 'Handebol'] },
        { id: 'nomeAluno', type: 'text', label: 'Nome do Aluno', required: true },
        { id: 'dataNascimento', type: 'date', label: 'Data de Nascimento', required: true },
        { id: 'categoria', type: 'select', label: 'Categoria', required: true, options: ['Sub-8', 'Sub-10', 'Sub-12', 'Sub-14', 'Sub-16', 'Sub-18', 'Adulto'] },
        { id: 'nomeResponsavel', type: 'text', label: 'Nome do Responsável', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
        { id: 'experienciaAnterior', type: 'select', label: 'Experiência Anterior', required: true, options: ['Sim', 'Não'] },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['RG', 'CPF', 'Atestado médico', 'Foto 3x4'],
    estimatedDays: 10,
    priority: 4,
    icon: 'Users',
    color: '#3b82f6',
  },
  {
    name: 'Cadastro de Atleta',
    description: 'Cadastrar atleta para representar o município',
    category: 'Cadastro',
    departmentCode: 'ESPORTE_LAZER',
    serviceType: 'COM_DADOS',
    moduleType: 'CADASTRO_ATLETA',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'nomeAtleta', type: 'text', label: 'Nome Completo', required: true },
        { id: 'cpf', type: 'text', label: 'CPF', required: true },
        { id: 'dataNascimento', type: 'date', label: 'Data de Nascimento', required: true },
        { id: 'modalidade', type: 'text', label: 'Modalidade', required: true },
        { id: 'categoria', type: 'select', label: 'Categoria', required: true, options: ['Amador', 'Federado', 'Profissional'] },
        { id: 'conquistas', type: 'textarea', label: 'Principais Conquistas', required: false },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['RG', 'CPF', 'Atestado médico', 'Comprovante de residência'],
    estimatedDays: 7,
    priority: 3,
    icon: 'Medal',
    color: '#eab308',
  },
  {
    name: 'Reserva de Espaço Esportivo',
    description: 'Reservar quadras, campos e ginásios municipais',
    category: 'Reserva',
    departmentCode: 'ESPORTE_LAZER',
    serviceType: 'COM_DADOS',
    moduleType: 'RESERVA_ESPACO_ESPORTIVO',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'espaco', type: 'select', label: 'Espaço', required: true, options: ['Ginásio Municipal', 'Campo de Futebol', 'Quadra Poliesportiva', 'Pista de Atletismo', 'Piscina'] },
        { id: 'dataReserva', type: 'date', label: 'Data', required: true },
        { id: 'horarioInicio', type: 'text', label: 'Horário de Início', required: true },
        { id: 'horarioFim', type: 'text', label: 'Horário de Término', required: true },
        { id: 'finalidade', type: 'select', label: 'Finalidade', required: true, options: ['Treino', 'Jogo', 'Torneio', 'Evento', 'Aula'] },
        { id: 'responsavel', type: 'text', label: 'Responsável', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['RG', 'CPF do responsável'],
    estimatedDays: 5,
    priority: 3,
    icon: 'Building',
    color: '#10b981',
  },
  {
    name: 'Inscrição em Competição',
    description: 'Inscrever-se em competições esportivas municipais',
    category: 'Competições',
    departmentCode: 'ESPORTE_LAZER',
    serviceType: 'COM_DADOS',
    moduleType: 'INSCRICAO_COMPETICAO',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'nomeCompeticao', type: 'text', label: 'Nome da Competição', required: true },
        { id: 'modalidade', type: 'text', label: 'Modalidade', required: true },
        { id: 'categoria', type: 'select', label: 'Categoria', required: true, options: ['Individual', 'Dupla', 'Equipe'] },
        { id: 'nomeParticipante', type: 'text', label: 'Nome do Participante/Equipe', required: true },
        { id: 'representante', type: 'text', label: 'Representante Legal', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['Ficha de inscrição', 'Atestado médico', 'RG'],
    estimatedDays: 7,
    priority: 4,
    icon: 'Trophy',
    color: '#eab308',
  },
  {
    name: 'Cadastro de Equipe Esportiva',
    description: 'Cadastrar equipe esportiva no município',
    category: 'Cadastro',
    departmentCode: 'ESPORTE_LAZER',
    serviceType: 'COM_DADOS',
    moduleType: 'CADASTRO_EQUIPE_ESPORTIVA',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'nomeEquipe', type: 'text', label: 'Nome da Equipe', required: true },
        { id: 'modalidade', type: 'text', label: 'Modalidade', required: true },
        { id: 'categoria', type: 'select', label: 'Categoria', required: true, options: ['Base', 'Juvenil', 'Adulto', 'Master'] },
        { id: 'responsavel', type: 'text', label: 'Responsável/Técnico', required: true },
        { id: 'numeroAtletas', type: 'number', label: 'Número de Atletas', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['Lista de atletas', 'RG do responsável'],
    estimatedDays: 10,
    priority: 3,
    icon: 'Users',
    color: '#3b82f6',
  },
  {
    name: 'Inscrição em Torneio',
    description: 'Inscrever equipe em torneios municipais',
    category: 'Torneios',
    departmentCode: 'ESPORTE_LAZER',
    serviceType: 'COM_DADOS',
    moduleType: 'INSCRICAO_TORNEIO',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'nomeTorneio', type: 'text', label: 'Nome do Torneio', required: true },
        { id: 'nomeEquipe', type: 'text', label: 'Nome da Equipe', required: true },
        { id: 'modalidade', type: 'text', label: 'Modalidade', required: true },
        { id: 'responsavel', type: 'text', label: 'Responsável', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['Súmula da equipe', 'Atestados médicos'],
    estimatedDays: 7,
    priority: 4,
    icon: 'Award',
    color: '#f59e0b',
  },
  {
    name: 'Cadastro de Modalidade',
    description: 'Cadastrar nova modalidade esportiva no município',
    category: 'Gestão',
    departmentCode: 'ESPORTE_LAZER',
    serviceType: 'COM_DADOS',
    moduleType: 'CADASTRO_MODALIDADE',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'nomeModalidade', type: 'text', label: 'Nome da Modalidade', required: true },
        { id: 'tipo', type: 'select', label: 'Tipo', required: true, options: ['Individual', 'Coletivo', 'Dupla'] },
        { id: 'descricao', type: 'textarea', label: 'Descrição', required: true },
        { id: 'equipamentosNecessarios', type: 'textarea', label: 'Equipamentos Necessários', required: false },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 5,
    priority: 2,
    icon: 'Target',
    color: '#8b5cf6',
  },
  {
    name: 'Agenda de Eventos Esportivos',
    description: 'Consultar agenda de eventos esportivos do município',
    category: 'Informação',
    departmentCode: 'ESPORTE_LAZER',
    serviceType: 'INFORMATIVO',
    moduleType: null,
    formSchema: null,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 1,
    icon: 'CalendarDays',
    color: '#f59e0b',
  },

  // ========================================
  // SECRETARIA DE HABITAÇÃO (7 serviços)
  // ========================================
  {
    name: 'Atendimentos de Habitação',
    description: 'Registrar atendimentos gerais da secretaria de habitação',
    category: 'Atendimento',
    departmentCode: 'HABITACAO',
    serviceType: 'COM_DADOS',
    moduleType: 'ATENDIMENTOS_HABITACAO',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'assunto', type: 'textarea', label: 'Assunto', required: true },
        { id: 'tipo', type: 'select', label: 'Tipo', required: true, options: ['Informação', 'Inscrição', 'Acompanhamento', 'Reclamação'] },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 5,
    priority: 3,
    icon: 'Home',
    color: '#f59e0b',
  },
  {
    name: 'Inscrição em Programa Habitacional',
    description: 'Inscrever-se em programas de habitação popular',
    category: 'Programas',
    departmentCode: 'HABITACAO',
    serviceType: 'COM_DADOS',
    moduleType: 'INSCRICAO_PROGRAMA_HABITACIONAL',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'programa', type: 'select', label: 'Programa', required: true, options: ['Minha Casa Minha Vida', 'Lote Urbanizado', 'Melhorias Habitacionais', 'Casa Verde e Amarela'] },
        { id: 'nomeResponsavel', type: 'text', label: 'Nome do Responsável', required: true },
        { id: 'cpf', type: 'text', label: 'CPF', required: true },
        { id: 'rendaFamiliar', type: 'number', label: 'Renda Familiar (R$)', required: true },
        { id: 'numeroMembros', type: 'number', label: 'Número de Membros da Família', required: true },
        { id: 'situacaoAtual', type: 'select', label: 'Situação Atual de Moradia', required: true, options: ['Aluguel', 'Com Familiares', 'Cedido', 'Ocupação Irregular', 'Área de Risco'] },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['RG e CPF', 'Comprovante de renda', 'Comprovante de residência', 'Cadastro CadÚnico'],
    estimatedDays: 30,
    priority: 5,
    icon: 'Building2',
    color: '#ef4444',
  },
  {
    name: 'Regularização Fundiária',
    description: 'Solicitar regularização de terreno ou imóvel',
    category: 'Regularização',
    departmentCode: 'HABITACAO',
    serviceType: 'COM_DADOS',
    moduleType: 'REGULARIZACAO_FUNDIARIA',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'enderecoImovel', type: 'text', label: 'Endereço do Imóvel', required: true },
        { id: 'tipoImovel', type: 'select', label: 'Tipo', required: true, options: ['Residencial', 'Comercial', 'Misto'] },
        { id: 'tempoOcupacao', type: 'number', label: 'Tempo de Ocupação (anos)', required: true },
        { id: 'proprietario', type: 'text', label: 'Nome do Ocupante', required: true },
        { id: 'cpf', type: 'text', label: 'CPF', required: true },
        { id: 'documentosPosse', type: 'textarea', label: 'Documentos de Posse Disponíveis', required: false },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['RG e CPF', 'Comprovante de ocupação (contas, declarações)', 'Croqui do terreno'],
    estimatedDays: 90,
    priority: 4,
    icon: 'FileCheck',
    color: '#3b82f6',
  },
  {
    name: 'Solicitação de Auxílio Aluguel',
    description: 'Solicitar auxílio aluguel emergencial',
    category: 'Benefícios',
    departmentCode: 'HABITACAO',
    serviceType: 'COM_DADOS',
    moduleType: 'SOLICITACAO_AUXILIO_ALUGUEL',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'motivoSolicitacao', type: 'textarea', label: 'Motivo da Solicitação', required: true },
        { id: 'situacaoEmergencia', type: 'select', label: 'Situação', required: true, options: ['Despejo', 'Área de Risco', 'Desastre Natural', 'Violência Doméstica', 'Outros'] },
        { id: 'valorAluguel', type: 'number', label: 'Valor do Aluguel (R$)', required: true },
        { id: 'rendaFamiliar', type: 'number', label: 'Renda Familiar (R$)', required: true },
        { id: 'numeroMembros', type: 'number', label: 'Número de Membros', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['RG e CPF', 'Comprovante de renda', 'Contrato de aluguel', 'Laudo técnico (se aplicável)'],
    estimatedDays: 15,
    priority: 5,
    icon: 'HandCoins',
    color: '#ef4444',
  },
  {
    name: 'Cadastro de Unidade Habitacional',
    description: 'Cadastrar unidade habitacional no sistema',
    category: 'Cadastro',
    departmentCode: 'HABITACAO',
    serviceType: 'COM_DADOS',
    moduleType: 'CADASTRO_UNIDADE_HABITACIONAL',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'endereco', type: 'text', label: 'Endereço Completo', required: true },
        { id: 'tipo', type: 'select', label: 'Tipo', required: true, options: ['Casa', 'Apartamento', 'Sobrado', 'Kitnet'] },
        { id: 'quartos', type: 'number', label: 'Número de Quartos', required: true },
        { id: 'areaUtil', type: 'number', label: 'Área Útil (m²)', required: true },
        { id: 'situacao', type: 'select', label: 'Situação', required: true, options: ['Ocupada', 'Vaga', 'Em Construção', 'Reforma'] },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['Matrícula do imóvel', 'Projeto aprovado'],
    estimatedDays: 10,
    priority: 2,
    icon: 'Building',
    color: '#8b5cf6',
  },
  {
    name: 'Inscrição na Fila de Habitação',
    description: 'Entrar na fila de espera por moradia',
    category: 'Fila',
    departmentCode: 'HABITACAO',
    serviceType: 'COM_DADOS',
    moduleType: 'INSCRICAO_FILA_HABITACAO',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'nomeResponsavel', type: 'text', label: 'Nome Completo', required: true },
        { id: 'cpf', type: 'text', label: 'CPF', required: true },
        { id: 'nis', type: 'text', label: 'NIS', required: true },
        { id: 'rendaFamiliar', type: 'number', label: 'Renda Familiar (R$)', required: true },
        { id: 'numeroMembros', type: 'number', label: 'Membros da Família', required: true },
        { id: 'situacaoAtual', type: 'select', label: 'Situação Atual', required: true, options: ['Aluguel', 'Cedido', 'Ocupação Irregular', 'Área de Risco'] },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['RG e CPF', 'Cadastro CadÚnico', 'Comprovante de renda', 'Comprovante de residência'],
    estimatedDays: 7,
    priority: 4,
    icon: 'ListOrdered',
    color: '#10b981',
  },
  {
    name: 'Consulta de Programas Habitacionais',
    description: 'Consultar programas habitacionais disponíveis',
    category: 'Informação',
    departmentCode: 'HABITACAO',
    serviceType: 'INFORMATIVO',
    moduleType: null,
    formSchema: null,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 1,
    icon: 'Info',
    color: '#3b82f6',
  },

  // ============================================
  // MEIO AMBIENTE (7 serviços)
  // ============================================
  {
    name: 'Atendimentos de Meio Ambiente',
    description: 'Gerenciar atendimentos e demandas ambientais',
    category: 'Atendimento',
    departmentCode: 'MEIO_AMBIENTE',
    serviceType: 'COM_DADOS',
    moduleType: 'ATENDIMENTOS_MEIO_AMBIENTE',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoAtendimento', type: 'select', label: 'Tipo de Atendimento', required: true, options: ['Denúncia Ambiental', 'Solicitação de Informação', 'Orientação Técnica', 'Licenciamento', 'Fiscalização'] },
        { id: 'assunto', type: 'text', label: 'Assunto', required: true },
        { id: 'descricao', type: 'textarea', label: 'Descrição Detalhada', required: true },
        { id: 'localizacao', type: 'text', label: 'Localização', required: true },
        { id: 'urgencia', type: 'select', label: 'Urgência', required: true, options: ['Baixa', 'Média', 'Alta', 'Crítica'] },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 7,
    priority: 3,
    icon: 'Leaf',
    color: '#10b981',
  },
  {
    name: 'Denúncia Ambiental',
    description: 'Registrar denúncia de crime ou infração ambiental',
    category: 'Denúncia',
    departmentCode: 'MEIO_AMBIENTE',
    serviceType: 'COM_DADOS',
    moduleType: 'DENUNCIA_AMBIENTAL',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoDenuncia', type: 'select', label: 'Tipo de Denúncia', required: true, options: ['Desmatamento', 'Poluição de Água', 'Poluição de Ar', 'Lixo Irregular', 'Maus-tratos a Animais', 'Queimada', 'Outros'] },
        { id: 'localizacao', type: 'text', label: 'Localização Exata', required: true },
        { id: 'descricao', type: 'textarea', label: 'Descrição dos Fatos', required: true },
        { id: 'dataOcorrencia', type: 'date', label: 'Data da Ocorrência', required: true },
        { id: 'horaOcorrencia', type: 'text', label: 'Hora da Ocorrência', required: false },
        { id: 'identificacao', type: 'select', label: 'Denúncia', required: true, options: ['Identificada', 'Anônima'] },
        { id: 'telefone', type: 'tel', label: 'Telefone (Opcional)', required: false },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 5,
    priority: 5,
    icon: 'AlertTriangle',
    color: '#ef4444',
  },
  {
    name: 'Licenciamento Ambiental',
    description: 'Solicitar licença ambiental para atividades',
    category: 'Licenciamento',
    departmentCode: 'MEIO_AMBIENTE',
    serviceType: 'COM_DADOS',
    moduleType: 'LICENCIAMENTO_AMBIENTAL',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoLicenca', type: 'select', label: 'Tipo de Licença', required: true, options: ['Prévia (LP)', 'Instalação (LI)', 'Operação (LO)', 'Simplificada'] },
        { id: 'nomeEmpreendimento', type: 'text', label: 'Nome do Empreendimento', required: true },
        { id: 'cnpj', type: 'text', label: 'CNPJ', required: true },
        { id: 'tipoAtividade', type: 'select', label: 'Tipo de Atividade', required: true, options: ['Industrial', 'Comercial', 'Construção Civil', 'Agropecuária', 'Mineração', 'Outros'] },
        { id: 'endereco', type: 'text', label: 'Endereço do Empreendimento', required: true },
        { id: 'areaTotal', type: 'number', label: 'Área Total (m²)', required: true },
        { id: 'descricaoAtividade', type: 'textarea', label: 'Descrição da Atividade', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['EIA/RIMA ou Estudo Ambiental', 'Planta do empreendimento', 'Certidão de uso do solo', 'Outorga de água (se aplicável)'],
    estimatedDays: 45,
    priority: 4,
    icon: 'FileCheck',
    color: '#8b5cf6',
  },
  {
    name: 'Solicitação de Poda de Árvore',
    description: 'Solicitar autorização para poda de árvore',
    category: 'Autorização',
    departmentCode: 'MEIO_AMBIENTE',
    serviceType: 'COM_DADOS',
    moduleType: 'SOLICITACAO_PODA',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'endereco', type: 'text', label: 'Endereço da Árvore', required: true },
        { id: 'tipoArvore', type: 'text', label: 'Tipo/Espécie da Árvore', required: false },
        { id: 'motivoPoda', type: 'select', label: 'Motivo da Poda', required: true, options: ['Risco de Queda', 'Interfere em Rede Elétrica', 'Obstrução de Via', 'Doença', 'Outro'] },
        { id: 'descricao', type: 'textarea', label: 'Descrição do Problema', required: true },
        { id: 'urgente', type: 'checkbox', label: 'Situação Urgente', required: false },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 15,
    priority: 3,
    icon: 'TreeDeciduous',
    color: '#22c55e',
  },
  {
    name: 'Cadastro de Área Verde',
    description: 'Cadastrar área verde ou parque no sistema',
    category: 'Cadastro',
    departmentCode: 'MEIO_AMBIENTE',
    serviceType: 'COM_DADOS',
    moduleType: 'CADASTRO_AREA_VERDE',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'nomeArea', type: 'text', label: 'Nome da Área Verde', required: true },
        { id: 'tipo', type: 'select', label: 'Tipo', required: true, options: ['Parque', 'Praça', 'Bosque', 'Reserva', 'Área de Preservação'] },
        { id: 'endereco', type: 'text', label: 'Endereço/Localização', required: true },
        { id: 'areaTotal', type: 'number', label: 'Área Total (m²)', required: true },
        { id: 'descricao', type: 'textarea', label: 'Descrição e Características', required: true },
        { id: 'situacao', type: 'select', label: 'Situação Atual', required: true, options: ['Ativa', 'Em Implantação', 'Recuperação', 'Desativada'] },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['Matrícula do imóvel', 'Memorial descritivo', 'Planta de localização'],
    estimatedDays: 20,
    priority: 2,
    icon: 'Map',
    color: '#059669',
  },
  {
    name: 'Coleta Seletiva - Agendamento',
    description: 'Agendar coleta de resíduos especiais',
    category: 'Agendamento',
    departmentCode: 'MEIO_AMBIENTE',
    serviceType: 'COM_DADOS',
    moduleType: 'AGENDAMENTO_COLETA',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoResiduo', type: 'select', label: 'Tipo de Resíduo', required: true, options: ['Eletrônicos', 'Móveis', 'Entulho', 'Poda de Jardim', 'Óleo de Cozinha', 'Pilhas e Baterias'] },
        { id: 'quantidade', type: 'select', label: 'Quantidade Estimada', required: true, options: ['Pequena (sacolas)', 'Média (até 1m³)', 'Grande (mais de 1m³)'] },
        { id: 'endereco', type: 'text', label: 'Endereço para Coleta', required: true },
        { id: 'dataPreferencial', type: 'date', label: 'Data Preferencial', required: true },
        { id: 'periodoPreferencial', type: 'select', label: 'Período', required: true, options: ['Manhã (8h-12h)', 'Tarde (13h-17h)'] },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 7,
    priority: 3,
    icon: 'Recycle',
    color: '#0ea5e9',
  },
  {
    name: 'Consulta de Calendário Ambiental',
    description: 'Consultar calendário de eventos e ações ambientais',
    category: 'Informação',
    departmentCode: 'MEIO_AMBIENTE',
    serviceType: 'INFORMATIVO',
    moduleType: null,
    formSchema: null,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 1,
    icon: 'Calendar',
    color: '#10b981',
  },

  // ============================================
  // OBRAS PÚBLICAS (7 serviços)
  // ============================================
  {
    name: 'Atendimentos de Obras Públicas',
    description: 'Gerenciar solicitações e demandas de obras',
    category: 'Atendimento',
    departmentCode: 'OBRAS_PUBLICAS',
    serviceType: 'COM_DADOS',
    moduleType: 'ATENDIMENTOS_OBRAS',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoSolicitacao', type: 'select', label: 'Tipo de Solicitação', required: true, options: ['Pavimentação', 'Iluminação Pública', 'Sinalização', 'Drenagem', 'Calçada', 'Outro'] },
        { id: 'endereco', type: 'text', label: 'Endereço/Localização', required: true },
        { id: 'descricao', type: 'textarea', label: 'Descrição do Problema', required: true },
        { id: 'urgencia', type: 'select', label: 'Urgência', required: true, options: ['Baixa', 'Média', 'Alta', 'Emergencial'] },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 15,
    priority: 3,
    icon: 'HardHat',
    color: '#f59e0b',
  },
  {
    name: 'Solicitação de Reparo em Via Pública',
    description: 'Solicitar reparo em ruas, calçadas ou vias',
    category: 'Solicitação',
    departmentCode: 'OBRAS_PUBLICAS',
    serviceType: 'COM_DADOS',
    moduleType: 'SOLICITACAO_REPARO_VIA',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoReparo', type: 'select', label: 'Tipo de Reparo', required: true, options: ['Buraco', 'Calçada Quebrada', 'Drenagem Entupida', 'Asfalto Danificado', 'Meio-Fio', 'Outro'] },
        { id: 'endereco', type: 'text', label: 'Endereço Exato', required: true },
        { id: 'referencia', type: 'text', label: 'Ponto de Referência', required: false },
        { id: 'descricao', type: 'textarea', label: 'Descrição do Problema', required: true },
        { id: 'dimensaoEstimada', type: 'text', label: 'Dimensão Estimada', required: false },
        { id: 'riscoAcidente', type: 'checkbox', label: 'Risco de Acidente', required: false },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 20,
    priority: 4,
    icon: 'Construction',
    color: '#ef4444',
  },
  {
    name: 'Solicitação de Iluminação Pública',
    description: 'Solicitar instalação ou reparo de iluminação',
    category: 'Solicitação',
    departmentCode: 'OBRAS_PUBLICAS',
    serviceType: 'COM_DADOS',
    moduleType: 'SOLICITACAO_ILUMINACAO',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoSolicitacao', type: 'select', label: 'Tipo de Solicitação', required: true, options: ['Nova Instalação', 'Lâmpada Queimada', 'Poste Danificado', 'Fiação Exposta', 'Luz Acesa Durante o Dia'] },
        { id: 'endereco', type: 'text', label: 'Endereço', required: true },
        { id: 'numeroPoste', type: 'text', label: 'Número do Poste (se houver)', required: false },
        { id: 'descricao', type: 'textarea', label: 'Descrição', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 10,
    priority: 3,
    icon: 'Lightbulb',
    color: '#fbbf24',
  },
  {
    name: 'Autorização para Obra em Via Pública',
    description: 'Solicitar autorização para realizar obra em via pública',
    category: 'Autorização',
    departmentCode: 'OBRAS_PUBLICAS',
    serviceType: 'COM_DADOS',
    moduleType: 'AUTORIZACAO_OBRA_VIA',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoObra', type: 'select', label: 'Tipo de Obra', required: true, options: ['Construção', 'Reforma', 'Demolição', 'Escavação', 'Instalação de Rede', 'Outro'] },
        { id: 'requerente', type: 'text', label: 'Nome do Requerente', required: true },
        { id: 'cnpjCpf', type: 'text', label: 'CNPJ/CPF', required: true },
        { id: 'endereco', type: 'text', label: 'Endereço da Obra', required: true },
        { id: 'descricaoObra', type: 'textarea', label: 'Descrição da Obra', required: true },
        { id: 'dataInicio', type: 'date', label: 'Data de Início Prevista', required: true },
        { id: 'prazoObra', type: 'number', label: 'Prazo da Obra (dias)', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['Projeto da obra', 'ART do responsável técnico', 'Cronograma', 'Plano de segurança'],
    estimatedDays: 20,
    priority: 3,
    icon: 'FileCheck',
    color: '#8b5cf6',
  },
  {
    name: 'Cadastro de Obra Pública',
    description: 'Cadastrar nova obra pública no sistema',
    category: 'Cadastro',
    departmentCode: 'OBRAS_PUBLICAS',
    serviceType: 'COM_DADOS',
    moduleType: 'CADASTRO_OBRA_PUBLICA',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'nomeObra', type: 'text', label: 'Nome da Obra', required: true },
        { id: 'tipoObra', type: 'select', label: 'Tipo de Obra', required: true, options: ['Pavimentação', 'Construção de Prédio', 'Ponte/Viaduto', 'Drenagem', 'Praça', 'Outro'] },
        { id: 'endereco', type: 'text', label: 'Endereço/Localização', required: true },
        { id: 'descricao', type: 'textarea', label: 'Descrição da Obra', required: true },
        { id: 'orcamento', type: 'number', label: 'Orçamento (R$)', required: true },
        { id: 'prazoMeses', type: 'number', label: 'Prazo (meses)', required: true },
        { id: 'situacao', type: 'select', label: 'Situação', required: true, options: ['Planejada', 'Em Licitação', 'Em Andamento', 'Concluída', 'Paralisada'] },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['Projeto executivo', 'Orçamento detalhado', 'Cronograma'],
    estimatedDays: 30,
    priority: 2,
    icon: 'Building2',
    color: '#6366f1',
  },
  {
    name: 'Acompanhamento de Obras',
    description: 'Acompanhar andamento de obras públicas',
    category: 'Acompanhamento',
    departmentCode: 'OBRAS_PUBLICAS',
    serviceType: 'COM_DADOS',
    moduleType: 'ACOMPANHAMENTO_OBRAS',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'numeroObra', type: 'text', label: 'Número da Obra', required: true },
        { id: 'tipoAcompanhamento', type: 'select', label: 'Tipo de Acompanhamento', required: true, options: ['Medição', 'Fiscalização', 'Vistoria Técnica', 'Recebimento'] },
        { id: 'percentualExecutado', type: 'number', label: 'Percentual Executado (%)', required: true },
        { id: 'observacoes', type: 'textarea', label: 'Observações', required: true },
        { id: 'dataVistoria', type: 'date', label: 'Data da Vistoria', required: true },
        { id: 'responsavel', type: 'text', label: 'Responsável pela Vistoria', required: true },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 5,
    priority: 3,
    icon: 'ClipboardCheck',
    color: '#0ea5e9',
  },
  {
    name: 'Consulta de Obras em Andamento',
    description: 'Consultar lista de obras públicas em execução',
    category: 'Informação',
    departmentCode: 'OBRAS_PUBLICAS',
    serviceType: 'INFORMATIVO',
    moduleType: null,
    formSchema: null,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 1,
    icon: 'Info',
    color: '#3b82f6',
  },

  // ============================================
  // PLANEJAMENTO URBANO (9 serviços)
  // ============================================
  {
    name: 'Atendimentos de Planejamento',
    description: 'Gerenciar solicitações de planejamento urbano',
    category: 'Atendimento',
    departmentCode: 'PLANEJAMENTO_URBANO',
    serviceType: 'COM_DADOS',
    moduleType: 'ATENDIMENTOS_PLANEJAMENTO',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoAtendimento', type: 'select', label: 'Tipo de Atendimento', required: true, options: ['Consulta de Zoneamento', 'Análise de Projeto', 'Licenciamento', 'Informações Gerais', 'Outro'] },
        { id: 'assunto', type: 'text', label: 'Assunto', required: true },
        { id: 'descricao', type: 'textarea', label: 'Descrição', required: true },
        { id: 'endereco', type: 'text', label: 'Endereço (se aplicável)', required: false },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 10,
    priority: 3,
    icon: 'Building',
    color: '#6366f1',
  },
  {
    name: 'Consulta de Zoneamento',
    description: 'Consultar zoneamento de área ou terreno',
    category: 'Consulta',
    departmentCode: 'PLANEJAMENTO_URBANO',
    serviceType: 'COM_DADOS',
    moduleType: 'CONSULTA_ZONEAMENTO',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'endereco', type: 'text', label: 'Endereço do Terreno', required: true },
        { id: 'numeroMatricula', type: 'text', label: 'Número da Matrícula', required: false },
        { id: 'inscricaoCadastral', type: 'text', label: 'Inscrição Cadastral', required: false },
        { id: 'finalidadeConsulta', type: 'textarea', label: 'Finalidade da Consulta', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 7,
    priority: 3,
    icon: 'Map',
    color: '#8b5cf6',
  },
  {
    name: 'Aprovação de Projeto',
    description: 'Submeter projeto para aprovação urbanística',
    category: 'Aprovação',
    departmentCode: 'PLANEJAMENTO_URBANO',
    serviceType: 'COM_DADOS',
    moduleType: 'APROVACAO_PROJETO',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoProjeto', type: 'select', label: 'Tipo de Projeto', required: true, options: ['Residencial', 'Comercial', 'Industrial', 'Misto', 'Loteamento', 'Reforma', 'Outro'] },
        { id: 'nomeEmpreendimento', type: 'text', label: 'Nome do Empreendimento', required: true },
        { id: 'endereco', type: 'text', label: 'Endereço', required: true },
        { id: 'areaConstruida', type: 'number', label: 'Área Construída (m²)', required: true },
        { id: 'areaTerreno', type: 'number', label: 'Área do Terreno (m²)', required: true },
        { id: 'numeroUnidades', type: 'number', label: 'Número de Unidades', required: false },
        { id: 'descricao', type: 'textarea', label: 'Descrição do Projeto', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['Projeto arquitetônico completo', 'Memorial descritivo', 'ART do responsável técnico', 'Certidão de propriedade'],
    estimatedDays: 30,
    priority: 4,
    icon: 'FileCheck',
    color: '#3b82f6',
  },
  {
    name: 'Alvará de Construção',
    description: 'Solicitar alvará para construção',
    category: 'Licenciamento',
    departmentCode: 'PLANEJAMENTO_URBANO',
    serviceType: 'COM_DADOS',
    moduleType: 'ALVARA_CONSTRUCAO',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoObra', type: 'select', label: 'Tipo de Obra', required: true, options: ['Construção Nova', 'Reforma', 'Ampliação', 'Demolição', 'Regularização'] },
        { id: 'endereco', type: 'text', label: 'Endereço da Obra', required: true },
        { id: 'areaConstruir', type: 'number', label: 'Área a Construir (m²)', required: true },
        { id: 'numeroProjetoAprovado', type: 'text', label: 'Número do Projeto Aprovado', required: true },
        { id: 'responsavelTecnico', type: 'text', label: 'Responsável Técnico', required: true },
        { id: 'creaCau', type: 'text', label: 'CREA/CAU', required: true },
        { id: 'prazoObraMeses', type: 'number', label: 'Prazo da Obra (meses)', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['Projeto aprovado', 'ART de execução', 'Matrícula do imóvel', 'IPTU em dia'],
    estimatedDays: 15,
    priority: 4,
    icon: 'FileText',
    color: '#f59e0b',
  },
  {
    name: 'Habite-se / CND',
    description: 'Solicitar Habite-se ou Certidão Negativa de Débitos',
    category: 'Certidão',
    departmentCode: 'PLANEJAMENTO_URBANO',
    serviceType: 'COM_DADOS',
    moduleType: 'HABITE_SE',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoCertidao', type: 'select', label: 'Tipo de Certidão', required: true, options: ['Habite-se', 'CND (Certidão Negativa de Débitos)', 'Ambos'] },
        { id: 'endereco', type: 'text', label: 'Endereço do Imóvel', required: true },
        { id: 'numeroAlvara', type: 'text', label: 'Número do Alvará de Construção', required: true },
        { id: 'dataTerminoObra', type: 'date', label: 'Data de Término da Obra', required: true },
        { id: 'responsavelTecnico', type: 'text', label: 'Responsável Técnico', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['Alvará de construção', 'ART de execução baixada', 'Laudo de vistoria', 'IPTU em dia'],
    estimatedDays: 20,
    priority: 4,
    icon: 'Award',
    color: '#10b981',
  },
  {
    name: 'Licença para Loteamento',
    description: 'Solicitar licença para parcelamento do solo',
    category: 'Licenciamento',
    departmentCode: 'PLANEJAMENTO_URBANO',
    serviceType: 'COM_DADOS',
    moduleType: 'LICENCA_LOTEAMENTO',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'nomeLoteamento', type: 'text', label: 'Nome do Loteamento', required: true },
        { id: 'localizacao', type: 'text', label: 'Localização', required: true },
        { id: 'areaTotal', type: 'number', label: 'Área Total (m²)', required: true },
        { id: 'numeroLotes', type: 'number', label: 'Número de Lotes', required: true },
        { id: 'responsavelTecnico', type: 'text', label: 'Responsável Técnico', required: true },
        { id: 'descricao', type: 'textarea', label: 'Descrição do Projeto', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['Projeto de loteamento', 'Memorial descritivo', 'Estudo ambiental', 'Anuência de concessionárias', 'Certidão de propriedade'],
    estimatedDays: 60,
    priority: 5,
    icon: 'Grid3x3',
    color: '#8b5cf6',
  },
  {
    name: 'Regularização Fundiária',
    description: 'Solicitar regularização de imóvel ou área',
    category: 'Regularização',
    departmentCode: 'PLANEJAMENTO_URBANO',
    serviceType: 'COM_DADOS',
    moduleType: 'REGULARIZACAO_FUNDIARIA',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'endereco', type: 'text', label: 'Endereço do Imóvel', required: true },
        { id: 'tipoImovel', type: 'select', label: 'Tipo de Imóvel', required: true, options: ['Residencial', 'Comercial', 'Misto'] },
        { id: 'tempoPosseMora', type: 'number', label: 'Tempo de Posse/Moradia (anos)', required: true },
        { id: 'situacao', type: 'select', label: 'Situação', required: true, options: ['Sem Documentação', 'Construção Irregular', 'Loteamento Irregular', 'Ocupação'] },
        { id: 'descricao', type: 'textarea', label: 'Descrição da Situação', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['Documentos pessoais', 'Comprovante de residência', 'Histórico de ocupação', 'Plantas/croquis do imóvel'],
    estimatedDays: 90,
    priority: 4,
    icon: 'FileCheck',
    color: '#ef4444',
  },
  {
    name: 'Cadastro de Empreendimento',
    description: 'Cadastrar novo empreendimento no município',
    category: 'Cadastro',
    departmentCode: 'PLANEJAMENTO_URBANO',
    serviceType: 'COM_DADOS',
    moduleType: 'CADASTRO_EMPREENDIMENTO',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'nomeEmpreendimento', type: 'text', label: 'Nome do Empreendimento', required: true },
        { id: 'tipo', type: 'select', label: 'Tipo', required: true, options: ['Residencial', 'Comercial', 'Industrial', 'Misto', 'Institucional'] },
        { id: 'endereco', type: 'text', label: 'Endereço', required: true },
        { id: 'fase', type: 'select', label: 'Fase', required: true, options: ['Planejamento', 'Projeto', 'Aprovação', 'Em Construção', 'Concluído'] },
        { id: 'responsavel', type: 'text', label: 'Responsável', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 15,
    priority: 2,
    icon: 'Building2',
    color: '#6366f1',
  },
  {
    name: 'Consulta de Plano Diretor',
    description: 'Consultar informações do Plano Diretor Municipal',
    category: 'Informação',
    departmentCode: 'PLANEJAMENTO_URBANO',
    serviceType: 'INFORMATIVO',
    moduleType: null,
    formSchema: null,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 1,
    icon: 'BookOpen',
    color: '#3b82f6',
  },

  // ============================================
  // SEGURANÇA PÚBLICA (11 serviços)
  // ============================================
  {
    name: 'Registros de Ocorrências',
    description: 'Registrar ocorrências e boletins',
    category: 'Registro',
    departmentCode: 'SEGURANCA_PUBLICA',
    serviceType: 'COM_DADOS',
    moduleType: 'REGISTROS_OCORRENCIAS',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoOcorrencia', type: 'select', label: 'Tipo de Ocorrência', required: true, options: ['Perturbação do Sossego', 'Aglomeração', 'Briga', 'Suspeita', 'Acidente', 'Outros'] },
        { id: 'localizacao', type: 'text', label: 'Localização', required: true },
        { id: 'dataOcorrencia', type: 'date', label: 'Data da Ocorrência', required: true },
        { id: 'horaOcorrencia', type: 'text', label: 'Hora da Ocorrência', required: true },
        { id: 'descricao', type: 'textarea', label: 'Descrição Detalhada', required: true },
        { id: 'gravidade', type: 'select', label: 'Gravidade', required: true, options: ['Baixa', 'Média', 'Alta', 'Crítica'] },
        { id: 'telefoneContato', type: 'tel', label: 'Telefone de Contato', required: true },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 1,
    priority: 5,
    icon: 'AlertCircle',
    color: '#ef4444',
  },
  {
    name: 'Patrulhamento',
    description: 'Gerenciar rotas e ações de patrulhamento',
    category: 'Operacional',
    departmentCode: 'SEGURANCA_PUBLICA',
    serviceType: 'COM_DADOS',
    moduleType: 'PATRULHAMENTO',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoPatrulha', type: 'select', label: 'Tipo de Patrulha', required: true, options: ['Rotina', 'Especial', 'Preventiva', 'Reforço'] },
        { id: 'area', type: 'text', label: 'Área/Bairro', required: true },
        { id: 'dataInicio', type: 'date', label: 'Data de Início', required: true },
        { id: 'turno', type: 'select', label: 'Turno', required: true, options: ['Manhã', 'Tarde', 'Noite', 'Madrugada', '24h'] },
        { id: 'observacoes', type: 'textarea', label: 'Observações', required: false },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 4,
    icon: 'Shield',
    color: '#3b82f6',
  },
  {
    name: 'Câmeras de Monitoramento',
    description: 'Gerenciar sistema de videomonitoramento',
    category: 'Monitoramento',
    departmentCode: 'SEGURANCA_PUBLICA',
    serviceType: 'COM_DADOS',
    moduleType: 'CAMERAS_MONITORAMENTO',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'numeroCamara', type: 'text', label: 'Número da Câmera', required: true },
        { id: 'localizacao', type: 'text', label: 'Localização', required: true },
        { id: 'tipoSolicitacao', type: 'select', label: 'Tipo de Solicitação', required: true, options: ['Nova Instalação', 'Manutenção', 'Verificação de Imagens', 'Reposicionamento'] },
        { id: 'descricao', type: 'textarea', label: 'Descrição', required: true },
        { id: 'urgente', type: 'checkbox', label: 'Urgente', required: false },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 7,
    priority: 3,
    icon: 'Camera',
    color: '#6366f1',
  },
  {
    name: 'Controle de Rondas',
    description: 'Registrar e controlar rondas realizadas',
    category: 'Controle',
    departmentCode: 'SEGURANCA_PUBLICA',
    serviceType: 'COM_DADOS',
    moduleType: 'CONTROLE_RONDAS',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'numeroRonda', type: 'text', label: 'Número da Ronda', required: true },
        { id: 'dataRonda', type: 'date', label: 'Data da Ronda', required: true },
        { id: 'horaInicio', type: 'text', label: 'Hora de Início', required: true },
        { id: 'horaTermino', type: 'text', label: 'Hora de Término', required: true },
        { id: 'locaisVisitados', type: 'textarea', label: 'Locais Visitados', required: true },
        { id: 'ocorrenciasRegistradas', type: 'number', label: 'Número de Ocorrências', required: true },
        { id: 'observacoes', type: 'textarea', label: 'Observações', required: false },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 3,
    icon: 'Route',
    color: '#8b5cf6',
  },
  {
    name: 'Iluminação de Segurança',
    description: 'Solicitar melhorias na iluminação para segurança',
    category: 'Infraestrutura',
    departmentCode: 'SEGURANCA_PUBLICA',
    serviceType: 'COM_DADOS',
    moduleType: 'ILUMINACAO_SEGURANCA',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'localizacao', type: 'text', label: 'Localização', required: true },
        { id: 'tipoSolicitacao', type: 'select', label: 'Tipo de Solicitação', required: true, options: ['Nova Iluminação', 'Aumento de Intensidade', 'Reparo', 'Reposicionamento'] },
        { id: 'motivoSeguranca', type: 'textarea', label: 'Motivo (Questão de Segurança)', required: true },
        { id: 'areaEscura', type: 'checkbox', label: 'Área Totalmente Escura', required: false },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 15,
    priority: 4,
    icon: 'Lightbulb',
    color: '#f59e0b',
  },
  {
    name: 'Eventos de Segurança',
    description: 'Registrar eventos que necessitam segurança',
    category: 'Evento',
    departmentCode: 'SEGURANCA_PUBLICA',
    serviceType: 'COM_DADOS',
    moduleType: 'EVENTOS_SEGURANCA',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'nomeEvento', type: 'text', label: 'Nome do Evento', required: true },
        { id: 'dataEvento', type: 'date', label: 'Data do Evento', required: true },
        { id: 'horaInicio', type: 'text', label: 'Hora de Início', required: true },
        { id: 'horaTermino', type: 'text', label: 'Hora de Término', required: true },
        { id: 'localizacao', type: 'text', label: 'Localização', required: true },
        { id: 'publicoEstimado', type: 'number', label: 'Público Estimado', required: true },
        { id: 'tipoEvento', type: 'select', label: 'Tipo de Evento', required: true, options: ['Show', 'Festa', 'Evento Esportivo', 'Manifestação', 'Outro'] },
        { id: 'efetivo Necessário', type: 'number', label: 'Efetivo Necessário', required: false },
        { id: 'telefone', type: 'tel', label: 'Telefone do Responsável', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['Autorização do evento', 'Projeto de segurança (se aplicável)'],
    estimatedDays: 10,
    priority: 4,
    icon: 'Calendar',
    color: '#10b981',
  },
  {
    name: 'Cadastro de Guardas',
    description: 'Cadastrar guardas municipais no sistema',
    category: 'Cadastro',
    departmentCode: 'SEGURANCA_PUBLICA',
    serviceType: 'COM_DADOS',
    moduleType: 'CADASTRO_GUARDAS',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'nomeCompleto', type: 'text', label: 'Nome Completo', required: true },
        { id: 'cpf', type: 'text', label: 'CPF', required: true },
        { id: 'matricula', type: 'text', label: 'Matrícula', required: true },
        { id: 'dataAdmissao', type: 'date', label: 'Data de Admissão', required: true },
        { id: 'cargo', type: 'select', label: 'Cargo', required: true, options: ['Guarda', 'Cabo', 'Sargento', 'Inspetor', 'Comandante'] },
        { id: 'turno', type: 'select', label: 'Turno', required: true, options: ['Manhã', 'Tarde', 'Noite', 'Madrugada', 'Variável'] },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['Documentos pessoais', 'Certificado de curso', 'Atestado de antecedentes'],
    estimatedDays: 15,
    priority: 2,
    icon: 'UserPlus',
    color: '#3b82f6',
  },
  {
    name: 'Controle de Equipamentos',
    description: 'Gerenciar equipamentos da guarda municipal',
    category: 'Controle',
    departmentCode: 'SEGURANCA_PUBLICA',
    serviceType: 'COM_DADOS',
    moduleType: 'CONTROLE_EQUIPAMENTOS',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoEquipamento', type: 'select', label: 'Tipo de Equipamento', required: true, options: ['Viatura', 'Rádio', 'Arma', 'Colete', 'Câmera', 'Outro'] },
        { id: 'numeroPatrimonio', type: 'text', label: 'Número do Patrimônio', required: true },
        { id: 'situacao', type: 'select', label: 'Situação', required: true, options: ['Em Uso', 'Disponível', 'Manutenção', 'Baixado'] },
        { id: 'responsavel', type: 'text', label: 'Responsável', required: false },
        { id: 'observacoes', type: 'textarea', label: 'Observações', required: false },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 3,
    priority: 2,
    icon: 'Package',
    color: '#6366f1',
  },
  {
    name: 'Treinamentos',
    description: 'Gerenciar treinamentos da guarda municipal',
    category: 'Capacitação',
    departmentCode: 'SEGURANCA_PUBLICA',
    serviceType: 'COM_DADOS',
    moduleType: 'TREINAMENTOS',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'nomeTreinamento', type: 'text', label: 'Nome do Treinamento', required: true },
        { id: 'tipoTreinamento', type: 'select', label: 'Tipo', required: true, options: ['Formação', 'Capacitação', 'Reciclagem', 'Especialização'] },
        { id: 'dataInicio', type: 'date', label: 'Data de Início', required: true },
        { id: 'dataTermino', type: 'date', label: 'Data de Término', required: true },
        { id: 'cargaHoraria', type: 'number', label: 'Carga Horária (horas)', required: true },
        { id: 'instrutor', type: 'text', label: 'Instrutor', required: true },
        { id: 'vagasTotal', type: 'number', label: 'Total de Vagas', required: true },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 30,
    priority: 3,
    icon: 'GraduationCap',
    color: '#8b5cf6',
  },
  {
    name: 'Relatórios de Atividades',
    description: 'Gerar relatórios de atividades da guarda',
    category: 'Relatório',
    departmentCode: 'SEGURANCA_PUBLICA',
    serviceType: 'COM_DADOS',
    moduleType: 'RELATORIOS_ATIVIDADES',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoRelatorio', type: 'select', label: 'Tipo de Relatório', required: true, options: ['Diário', 'Semanal', 'Mensal', 'Anual', 'Especial'] },
        { id: 'periodoInicio', type: 'date', label: 'Período - Início', required: true },
        { id: 'periodoFim', type: 'date', label: 'Período - Fim', required: true },
        { id: 'area', type: 'text', label: 'Área/Setor', required: false },
        { id: 'descricao', type: 'textarea', label: 'Descrição/Observações', required: false },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 5,
    priority: 2,
    icon: 'FileText',
    color: '#0ea5e9',
  },
  {
    name: 'Consulta de Estatísticas de Segurança',
    description: 'Consultar estatísticas e indicadores de segurança',
    category: 'Informação',
    departmentCode: 'SEGURANCA_PUBLICA',
    serviceType: 'INFORMATIVO',
    moduleType: null,
    formSchema: null,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 1,
    icon: 'BarChart',
    color: '#3b82f6',
  },

  // ============================================
  // SERVIÇOS PÚBLICOS (9 serviços)
  // ============================================
  {
    name: 'Atendimentos de Serviços Públicos',
    description: 'Gerenciar solicitações gerais de serviços públicos',
    category: 'Atendimento',
    departmentCode: 'SERVICOS_PUBLICOS',
    serviceType: 'COM_DADOS',
    moduleType: 'ATENDIMENTOS_SERVICOS_PUBLICOS',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoServico', type: 'select', label: 'Tipo de Serviço', required: true, options: ['Limpeza Pública', 'Coleta de Lixo', 'Manutenção de Praças', 'Poda de Árvores', 'Dedetização', 'Outro'] },
        { id: 'endereco', type: 'text', label: 'Endereço', required: true },
        { id: 'descricao', type: 'textarea', label: 'Descrição da Solicitação', required: true },
        { id: 'urgencia', type: 'select', label: 'Urgência', required: true, options: ['Baixa', 'Média', 'Alta', 'Emergencial'] },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 10,
    priority: 3,
    icon: 'Wrench',
    color: '#6366f1',
  },
  {
    name: 'Limpeza Urbana',
    description: 'Solicitar limpeza de vias, praças e espaços públicos',
    category: 'Limpeza',
    departmentCode: 'SERVICOS_PUBLICOS',
    serviceType: 'COM_DADOS',
    moduleType: 'LIMPEZA_URBANA',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoLimpeza', type: 'select', label: 'Tipo de Limpeza', required: true, options: ['Varrição', 'Capina', 'Desobstrução de Bueiro', 'Limpeza de Praça', 'Coleta de Entulho', 'Outro'] },
        { id: 'endereco', type: 'text', label: 'Endereço', required: true },
        { id: 'referencia', type: 'text', label: 'Ponto de Referência', required: false },
        { id: 'descricao', type: 'textarea', label: 'Descrição', required: true },
        { id: 'dimensaoEstimada', type: 'text', label: 'Dimensão/Extensão', required: false },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 7,
    priority: 3,
    icon: 'Broom',
    color: '#10b981',
  },
  {
    name: 'Coleta de Lixo',
    description: 'Reportar problema ou solicitar coleta especial',
    category: 'Coleta',
    departmentCode: 'SERVICOS_PUBLICOS',
    serviceType: 'COM_DADOS',
    moduleType: 'COLETA_LIXO',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoSolicitacao', type: 'select', label: 'Tipo de Solicitação', required: true, options: ['Coleta não Realizada', 'Horário Irregular', 'Coleta Especial', 'Entulho/Grande Volume', 'Outro'] },
        { id: 'endereco', type: 'text', label: 'Endereço', required: true },
        { id: 'diaColeta', type: 'select', label: 'Dia da Coleta', required: false, options: ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'] },
        { id: 'descricao', type: 'textarea', label: 'Descrição', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 5,
    priority: 4,
    icon: 'Trash2',
    color: '#ef4444',
  },
  {
    name: 'Manutenção de Praças e Jardins',
    description: 'Solicitar manutenção de praças e áreas verdes',
    category: 'Manutenção',
    departmentCode: 'SERVICOS_PUBLICOS',
    serviceType: 'COM_DADOS',
    moduleType: 'MANUTENCAO_PRACAS',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'nomePraca', type: 'text', label: 'Nome da Praça/Jardim', required: true },
        { id: 'endereco', type: 'text', label: 'Endereço', required: true },
        { id: 'tipoManutencao', type: 'select', label: 'Tipo de Manutenção', required: true, options: ['Poda', 'Jardinagem', 'Irrigação', 'Limpeza', 'Equipamento Quebrado', 'Outro'] },
        { id: 'descricao', type: 'textarea', label: 'Descrição do Problema', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 15,
    priority: 3,
    icon: 'TreePine',
    color: '#22c55e',
  },
  {
    name: 'Cemitérios',
    description: 'Serviços relacionados aos cemitérios municipais',
    category: 'Cemitério',
    departmentCode: 'SERVICOS_PUBLICOS',
    serviceType: 'COM_DADOS',
    moduleType: 'CEMITERIOS',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoSolicitacao', type: 'select', label: 'Tipo de Solicitação', required: true, options: ['Sepultamento', 'Exumação', 'Manutenção de Túmulo', 'Construção de Jazigo', 'Informações', 'Outro'] },
        { id: 'nomeFalecido', type: 'text', label: 'Nome do Falecido (se aplicável)', required: false },
        { id: 'cemiterio', type: 'text', label: 'Cemitério', required: true },
        { id: 'descricao', type: 'textarea', label: 'Descrição', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['Atestado de óbito (se aplicável)', 'Documentos pessoais'],
    estimatedDays: 3,
    priority: 5,
    icon: 'Cross',
    color: '#64748b',
  },
  {
    name: 'Mercado e Feiras',
    description: 'Gerenciar feiras livres e mercado municipal',
    category: 'Feira',
    departmentCode: 'SERVICOS_PUBLICOS',
    serviceType: 'COM_DADOS',
    moduleType: 'MERCADO_FEIRAS',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoSolicitacao', type: 'select', label: 'Tipo de Solicitação', required: true, options: ['Nova Barraca', 'Transferência de Barraca', 'Manutenção', 'Reclamação', 'Informações'] },
        { id: 'localFeira', type: 'text', label: 'Local da Feira', required: true },
        { id: 'diaFeira', type: 'select', label: 'Dia da Feira', required: false, options: ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado', 'Domingo'] },
        { id: 'tipoComercio', type: 'text', label: 'Tipo de Comércio', required: false },
        { id: 'descricao', type: 'textarea', label: 'Descrição', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 15,
    priority: 3,
    icon: 'Store',
    color: '#f59e0b',
  },
  {
    name: 'Controle de Zoonoses',
    description: 'Serviços de controle de animais e zoonoses',
    category: 'Zoonoses',
    departmentCode: 'SERVICOS_PUBLICOS',
    serviceType: 'COM_DADOS',
    moduleType: 'CONTROLE_ZOONOSES',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoSolicitacao', type: 'select', label: 'Tipo de Solicitação', required: true, options: ['Dedetização', 'Desratização', 'Controle de Escorpiões', 'Animal Morto', 'Captura de Animal', 'Vacinação Antirrábica', 'Outro'] },
        { id: 'endereco', type: 'text', label: 'Endereço', required: true },
        { id: 'tipoAnimal', type: 'text', label: 'Tipo de Animal/Praga', required: false },
        { id: 'descricao', type: 'textarea', label: 'Descrição', required: true },
        { id: 'urgente', type: 'checkbox', label: 'Situação Urgente', required: false },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 7,
    priority: 4,
    icon: 'Bug',
    color: '#ef4444',
  },
  {
    name: 'Transporte Público',
    description: 'Solicitações sobre transporte público municipal',
    category: 'Transporte',
    departmentCode: 'SERVICOS_PUBLICOS',
    serviceType: 'COM_DADOS',
    moduleType: 'TRANSPORTE_PUBLICO',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoSolicitacao', type: 'select', label: 'Tipo de Solicitação', required: true, options: ['Nova Linha', 'Alteração de Itinerário', 'Reclamação', 'Ponto de Ônibus', 'Horário', 'Outro'] },
        { id: 'linha', type: 'text', label: 'Linha (se aplicável)', required: false },
        { id: 'endereco', type: 'text', label: 'Endereço/Local', required: true },
        { id: 'descricao', type: 'textarea', label: 'Descrição', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 20,
    priority: 3,
    icon: 'Bus',
    color: '#3b82f6',
  },
  {
    name: 'Consulta de Calendário de Coleta',
    description: 'Consultar horários e dias de coleta de lixo',
    category: 'Informação',
    departmentCode: 'SERVICOS_PUBLICOS',
    serviceType: 'INFORMATIVO',
    moduleType: null,
    formSchema: null,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 1,
    icon: 'Calendar',
    color: '#10b981',
  },

  // ============================================
  // TURISMO (9 serviços)
  // ============================================
  {
    name: 'Atendimentos de Turismo',
    description: 'Gerenciar solicitações turísticas',
    category: 'Atendimento',
    departmentCode: 'TURISMO',
    serviceType: 'COM_DADOS',
    moduleType: 'ATENDIMENTOS_TURISMO',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoSolicitacao', type: 'select', label: 'Tipo de Solicitação', required: true, options: ['Informação Turística', 'Evento', 'Credenciamento', 'Roteiro', 'Outro'] },
        { id: 'assunto', type: 'text', label: 'Assunto', required: true },
        { id: 'descricao', type: 'textarea', label: 'Descrição', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
        { id: 'email', type: 'email', label: 'Email', required: false },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 7,
    priority: 3,
    icon: 'Compass',
    color: '#06b6d4',
  },
  {
    name: 'Cadastro de Pontos Turísticos',
    description: 'Cadastrar atrativos e pontos turísticos',
    category: 'Cadastro',
    departmentCode: 'TURISMO',
    serviceType: 'COM_DADOS',
    moduleType: 'CADASTRO_PONTOS_TURISTICOS',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'nomePonto', type: 'text', label: 'Nome do Ponto Turístico', required: true },
        { id: 'tipo', type: 'select', label: 'Tipo', required: true, options: ['Natural', 'Histórico', 'Cultural', 'Religioso', 'Gastronômico', 'Entretenimento', 'Outro'] },
        { id: 'endereco', type: 'text', label: 'Endereço', required: true },
        { id: 'descricao', type: 'textarea', label: 'Descrição', required: true },
        { id: 'horarioFuncionamento', type: 'text', label: 'Horário de Funcionamento', required: false },
        { id: 'telefoneContato', type: 'tel', label: 'Telefone de Contato', required: false },
        { id: 'acessibilidade', type: 'checkbox', label: 'Possui Acessibilidade', required: false },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 10,
    priority: 2,
    icon: 'MapPin',
    color: '#ef4444',
  },
  {
    name: 'Credenciamento de Guias',
    description: 'Credenciar guias turísticos no município',
    category: 'Credenciamento',
    departmentCode: 'TURISMO',
    serviceType: 'COM_DADOS',
    moduleType: 'CREDENCIAMENTO_GUIAS',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'nomeCompleto', type: 'text', label: 'Nome Completo', required: true },
        { id: 'cpf', type: 'text', label: 'CPF', required: true },
        { id: 'cadastur', type: 'text', label: 'Número CADASTUR', required: false },
        { id: 'idiomas', type: 'text', label: 'Idiomas', required: true },
        { id: 'especialidade', type: 'select', label: 'Especialidade', required: true, options: ['Turismo Cultural', 'Turismo de Aventura', 'Ecoturismo', 'Turismo Religioso', 'Geral'] },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
        { id: 'email', type: 'email', label: 'Email', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['RG e CPF', 'Certificado de curso de guia', 'Foto 3x4', 'Comprovante de residência'],
    estimatedDays: 20,
    priority: 3,
    icon: 'UserCheck',
    color: '#8b5cf6',
  },
  {
    name: 'Eventos Turísticos',
    description: 'Cadastrar e gerenciar eventos turísticos',
    category: 'Evento',
    departmentCode: 'TURISMO',
    serviceType: 'COM_DADOS',
    moduleType: 'EVENTOS_TURISTICOS',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'nomeEvento', type: 'text', label: 'Nome do Evento', required: true },
        { id: 'tipoEvento', type: 'select', label: 'Tipo de Evento', required: true, options: ['Festival', 'Feira', 'Show', 'Exposição', 'Festa Tradicional', 'Esportivo', 'Outro'] },
        { id: 'dataInicio', type: 'date', label: 'Data de Início', required: true },
        { id: 'dataTermino', type: 'date', label: 'Data de Término', required: true },
        { id: 'localizacao', type: 'text', label: 'Localização', required: true },
        { id: 'publicoEstimado', type: 'number', label: 'Público Estimado', required: false },
        { id: 'descricao', type: 'textarea', label: 'Descrição', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone do Responsável', required: true },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 15,
    priority: 3,
    icon: 'Calendar',
    color: '#f59e0b',
  },
  {
    name: 'Hospedagem - Credenciamento',
    description: 'Credenciar meios de hospedagem',
    category: 'Credenciamento',
    departmentCode: 'TURISMO',
    serviceType: 'COM_DADOS',
    moduleType: 'CREDENCIAMENTO_HOSPEDAGEM',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'nomeEstabelecimento', type: 'text', label: 'Nome do Estabelecimento', required: true },
        { id: 'tipoHospedagem', type: 'select', label: 'Tipo de Hospedagem', required: true, options: ['Hotel', 'Pousada', 'Hostel', 'Apart-hotel', 'Camping', 'Outro'] },
        { id: 'cnpj', type: 'text', label: 'CNPJ', required: true },
        { id: 'endereco', type: 'text', label: 'Endereço', required: true },
        { id: 'numeroQuartos', type: 'number', label: 'Número de Quartos/Unidades', required: true },
        { id: 'capacidadeHospedes', type: 'number', label: 'Capacidade de Hóspedes', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
        { id: 'email', type: 'email', label: 'Email', required: true },
      ],
    },
    requiresDocuments: true,
    requiredDocuments: ['CNPJ', 'Alvará de funcionamento', 'Cadastur (se houver)', 'Projeto arquitetônico'],
    estimatedDays: 30,
    priority: 3,
    icon: 'Hotel',
    color: '#3b82f6',
  },
  {
    name: 'Roteiros Turísticos',
    description: 'Criar e gerenciar roteiros turísticos',
    category: 'Roteiro',
    departmentCode: 'TURISMO',
    serviceType: 'COM_DADOS',
    moduleType: 'ROTEIROS_TURISTICOS',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'nomeRoteiro', type: 'text', label: 'Nome do Roteiro', required: true },
        { id: 'tipoRoteiro', type: 'select', label: 'Tipo de Roteiro', required: true, options: ['Histórico', 'Cultural', 'Ecológico', 'Gastronômico', 'Religioso', 'Aventura', 'Misto'] },
        { id: 'duracao', type: 'text', label: 'Duração', required: true },
        { id: 'descricao', type: 'textarea', label: 'Descrição do Roteiro', required: true },
        { id: 'pontosVisitados', type: 'textarea', label: 'Pontos Visitados', required: true },
        { id: 'nivelDificuldade', type: 'select', label: 'Nível de Dificuldade', required: false, options: ['Fácil', 'Moderado', 'Difícil'] },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 15,
    priority: 2,
    icon: 'Route',
    color: '#10b981',
  },
  {
    name: 'Sinalização Turística',
    description: 'Solicitar instalação de placas turísticas',
    category: 'Infraestrutura',
    departmentCode: 'TURISMO',
    serviceType: 'COM_DADOS',
    moduleType: 'SINALIZACAO_TURISTICA',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'tipoSolicitacao', type: 'select', label: 'Tipo de Solicitação', required: true, options: ['Nova Placa', 'Manutenção', 'Substituição', 'Remoção'] },
        { id: 'localizacao', type: 'text', label: 'Localização', required: true },
        { id: 'destino', type: 'text', label: 'Destino/Atração', required: true },
        { id: 'descricao', type: 'textarea', label: 'Descrição', required: true },
        { id: 'telefone', type: 'tel', label: 'Telefone', required: true },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 20,
    priority: 3,
    icon: 'Signpost',
    color: '#f59e0b',
  },
  {
    name: 'Pesquisa de Satisfação Turística',
    description: 'Coletar feedback de turistas',
    category: 'Pesquisa',
    departmentCode: 'TURISMO',
    serviceType: 'COM_DADOS',
    moduleType: 'PESQUISA_SATISFACAO',
    formSchema: {
      type: 'object',
      fields: [
        { id: 'origem', type: 'text', label: 'Cidade/Estado de Origem', required: true },
        { id: 'motivoVisita', type: 'select', label: 'Motivo da Visita', required: true, options: ['Lazer', 'Negócios', 'Visita a Parentes', 'Evento', 'Outro'] },
        { id: 'duracaoEstadia', type: 'select', label: 'Duração da Estadia', required: true, options: ['Bate-volta', '1-2 dias', '3-5 dias', '6-10 dias', 'Mais de 10 dias'] },
        { id: 'avaliacaoGeral', type: 'select', label: 'Avaliação Geral', required: true, options: ['Excelente', 'Bom', 'Regular', 'Ruim', 'Péssimo'] },
        { id: 'sugestoes', type: 'textarea', label: 'Sugestões/Comentários', required: false },
        { id: 'email', type: 'email', label: 'Email (Opcional)', required: false },
      ],
    },
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 2,
    icon: 'MessageSquare',
    color: '#06b6d4',
  },
  {
    name: 'Consulta de Mapas e Guias',
    description: 'Consultar mapas turísticos e guias da cidade',
    category: 'Informação',
    departmentCode: 'TURISMO',
    serviceType: 'INFORMATIVO',
    moduleType: null,
    formSchema: null,
    requiresDocuments: false,
    estimatedDays: 0,
    priority: 1,
    icon: 'Map',
    color: '#3b82f6',
  },
];

export default SERVICES_COMPLETE_DATA;
